### ISSUE TITLE
Helm deploy failed with ClickHouse migrate failed if cluster name contain '-'

### ISSUE THREAD

**Issue by wbchn** [PostHog/posthog#10233]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

External clickhouse cluster name causes migration error.

we used https://github.com/PostHog/charts-clickhouse to deploy posthog to k8s cluster with self-hosted clickhouse cluster.

values.yaml:
```
externalClickhouse:
  host: clickhouse-lb.clickhouse
  cluster: test-cluster
  database: posthog
```

but cluster name contain '-' , which causes the error: 

```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/posthog/code/ee/management/commands/migrate_clickhouse.py", line 42, in handle
    self.migrate(CLICKHOUSE_HTTP_URL, options)
  File "/home/posthog/code/ee/management/commands/migrate_clickhouse.py", line 80, in migrate
    database.migrate(MIGRATIONS_PACKAGE_NAME, options["upto"], replicated=CLICKHOUSE_REPLICATION)
  File "/usr/local/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 352, in migrate
    operation.apply(self)
  File "/usr/local/lib/python3.8/site-packages/infi/clickhouse_orm/migrations.py", line 271, in apply
    database.raw(item)
  File "/usr/local/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 295, in raw
    return self._send(query, settings=settings, stream=stream).text
  File "/usr/local/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 389, in _send
    raise ServerError(r.text)
infi.clickhouse_orm.database.ServerError: Code: 62. DB::Exception: Syntax error: failed at position 67 ('-'): -cluster. Expected one of: NO DELAY, end of query, INTO OUTFILE, SETTINGS, FORMAT, SYNC. (SYNTAX_ERROR) (version 21.11.3.6 (official build))

```

## How to reproduce

1. create a clickhouse with cluster name contain '-', such as 'test-cluster'
2. using [helm-chart](https://github.com/PostHog/charts-clickhouse) to deploy posthog with external clickhouse config.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

checked the migrate code:
This is error: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/migrations/0028_dead_letter_queue_settings.py#L7-L8
But this is ok: https://github.com/PostHog/posthog/blob/master/ee/clickhouse/migrations/0023_dead_letter_queue_tags.py

The code should be:
```
# this is error
f"DROP TABLE IF EXISTS events_dead_letter_queue_mv ON CLUSTER {CLICKHOUSE_CLUSTER}"

# change to(like 0023_dead_letter_queue_tags.py)
f"DROP TABLE IF EXISTS events_dead_letter_queue_mv ON CLUSTER '{CLICKHOUSE_CLUSTER}'"
```

**Comment by macobo** [comment]
Good catch! Note that if you got this far with your investigations, a PR wouldn't have hurt. Fixing this in https://github.com/PostHog/posthog/pull/10235, should be alive again next release :)

**Comment by wbchn** [comment]
Thanks for the quick fix. I'll close this issue.
