### ISSUE TITLE
Crashing on experiments pages

### ISSUE THREAD

**Issue by calvinwoo** [PostHog/posthog#10724]
## Bug description

If I navigate to the page for a specific experiment, the page crashes.

![Screen Shot 2022-07-11 at 10 17 50 PM](https://user-images.githubusercontent.com/1356668/178414555-9699dfe3-7e3a-4d92-ae24-f877f3bcb368.png)

## How to reproduce

1. Click on experiments
2. Click on a specific experiment
3. Page crashes

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Javascript logs in devtools:
```
react_devtools_backend.js:4026 TypeError: s.properties?.some is not a function
    at insightLogic.ts:633:47
    at Array.some (<anonymous>)
    at lt.selectors.isUsingSessionAnalysis (insightLogic.ts:632:71)
    at index.js:87:25
    at c (defaultMemoize.js:135:20)
    at index.js:101:40
    at Object.c [as isUsingSessionAnalysis] (defaultMemoize.js:135:20)
    at index.cjs.js:1491:31
    at index.cjs.js:593:12
    at Object.I_ [as useSyncExternalStore] (index.cjs.js:441:28)
    at ld (index.cjs.js:592:23)
    at Object.get (index.cjs.js:605:18)
    at Lm (InsightContainer.tsx:72:9)
    at r3 (react-dom.production.min.js:153:146)
    at wQ (react-dom.production.min.js:261:496)
    at EQ (react-dom.production.min.js:246:265)
    at Bke (react-dom.production.min.js:246:194)
    at gq (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at Er.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Yf (react-dom.production.min.js:122:325)
    at $G (react-dom.production.min.js:123:61)
    at Pu (react-dom.production.min.js:122:496)
    at zf (react-dom.production.min.js:230:156)
    at rQ (react-dom.production.min.js:163:512)
    at index.cjs.js:441:263
    at s (index.cjs.js:763:11)
    at Object.f [as dispatch] (redux.js:305:7)
    at e (<anonymous>:2494:20)
    at index.ts:51:26
    at index.ts:71:26
    at Object.dispatch (index.cjs.js:1777:28)
    at Object.dispatch (<anonymous>:3665:80)
    at t.actions.<computed> [as loadExperimentSuccess] (index.cjs.js:1152:28)
    at index.ts:150:45
```

**Comment by calvinwoo** [comment]
Looks like it's been resolved.
