### ISSUE TITLE
"Load suggestions on reducer Suggestions failed" after upgrading from 1.36.1 to 1.37

### ISSUE THREAD

**Issue by paulcwatts** [PostHog/posthog#10772]
## Bug description

I updated from 1.36.1 to 1.37 (Helm chart 22.1.2 to 23.4.0). When I did that, every time I access the web app, I get a notification in the bottom right of the page:

```
Load suggestions on reducer Suggestions failed: A server error occurred.
```

All of my async migrations are up-to-date  (0001 through 0004). For its part, the posthog web app says "All systems operational."

## How to reproduce

1. Update from 1.36.1 to 1.37 
2. Access the web app

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: 1.37, Helm Chart 24.3.0
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

In the web pod's logs I see this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/posthog/code/posthog/api/insight.py", line 545, in trend
    result = self.calculate_trends(request)
  File "/home/posthog/code/posthog/decorators.py", line 52, in wrapper
    fresh_result_package = cast(T, f(self, request))
  File "/home/posthog/code/posthog/api/insight.py", line 588, in calculate_trends
    result = trends_query.run(filter, team)
  File "/home/posthog/code/posthog/queries/trends/trends.py", line 202, in run
    result.extend(handle_compare(filter, self._run_query, team, entity=entity))
  File "/home/posthog/code/posthog/queries/base.py", line 51, in handle_compare
    trend_entity = func(filter=filter, team=team, **kwargs)
  File "/home/posthog/code/posthog/queries/trends/trends.py", line 125, in _run_query
    result = sync_execute(sql, params)
  File "/home/posthog/code/posthog/client.py", line 188, in sync_execute
    raise err
posthog.errors.CHQueryErrorSyntaxError: Code: 62.
DB::Exception: Syntax error: failed at position 183 ('(') (line 2, col 87): (
    SELECT SUM(total) as count, day_start, breakdown_value FROM (
        SELECT * FROM (
            SELECT
                toUInt16(0) AS total,
           . Unmatched parentheses: ((((([). Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb37173a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x16e453bf in /usr/bin/clickhouse
2. ? @ 0x15d259b8 in /usr/bin/clickhouse
3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x15d255f5 in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x168b0a3a in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x168c0399 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x19b801ef in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x19b82641 in /usr/bin/clickhouse
```

Original Slack Conversation: https://posthogusers.slack.com/archives/C01GLBKHKQT/p1657307440773989

**Comment by paulcwatts** [comment]
I updated from 22.1.2 to 23.5.1 and I didn't get this error. So ¯\_(ツ)_/¯, not sure what happened.
