### ISSUE TITLE
Table posthog.infi_clickhouse_orm_migrations doesn't exist

### ISSUE THREAD

**Issue by Jameslu041** [PostHog/posthog#10789]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

List of clickhouse migrations to be applied:
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/posthog/code/ee/management/commands/migrate_clickhouse.py", line 42, in handle
    self.migrate(CLICKHOUSE_HTTP_URL, options)
  File "/home/posthog/code/ee/management/commands/migrate_clickhouse.py", line 55, in migrate
    migrations = list(self.get_migrations(database, options["upto"]))
  File "/home/posthog/code/ee/management/commands/migrate_clickhouse.py", line 85, in get_migrations
    applied_migrations = self.get_applied_migrations(database)
  File "/home/posthog/code/ee/management/commands/migrate_clickhouse.py", line 95, in get_applied_migrations
    return database._get_applied_migrations(MIGRATIONS_PACKAGE_NAME, replicated=CLICKHOUSE_REPLICATION)
  File "/usr/local/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 379, in _get_applied_migrations
    return set(obj.module_name for obj in self.select(query))
  File "/usr/local/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 379, in <genexpr>
    return set(obj.module_name for obj in self.select(query))
  File "/usr/local/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 276, in select
    r = self._send(query, settings, True)
  File "/usr/local/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 389, in _send
    raise ServerError(r.text)
infi.clickhouse_orm.database.ServerError: Code: 60. DB::Exception: Table posthog.infi_clickhouse_orm_migrations doesn't exist. (UNKNOWN_TABLE) (version 22.3.7.28 (official build))
 (0)

## How to reproduce

1. hobby deploy
2. root_worker_1 always restarting
3. docker logs -f "restarting container"
4. get error message above

## Environment

- [x] self-hosted PostHog (ClickHouse-based), version/commit: 22.3.7.28

**Comment by jandolezal71** [comment]
#metoo https://github.com/PostHog/posthog/issues/10792

**Comment by timgl** [comment]
Closing as duplicate of #10792, can see you've responded to that issue as well
