### ISSUE TITLE
Worker fails if timestamp is invalid

### ISSUE THREAD

**Issue by 14MR** [PostHog/posthog#1180]
**Describe the bug**
`/capture/` endpoint doesn't validate "timestamp" field, so when workers tries to save invalid value into DB, it fails. 

**To Reproduce**
1. POST to `/capture/` with this body (replace with your api_key)
```
{
    "api_key": "YOUR_VALID_KEY",
    "event": "[event name]",
    "properties": {
        "distinct_id": "1",
        "key1": "value1",
        "key2": "value2"
    },
    "timestamp": "[optional timestamp in ISO 8601 format]"
}
```
2. wait until worker tries to insert data
3. take a look at the worker's log

**Expected behavior**
The data is inserted

**Screenshots**

![image](https://user-images.githubusercontent.com/5824170/87049794-b07ba000-c1fd-11ea-9998-4619abd9aeb5.png)
![image](https://user-images.githubusercontent.com/5824170/87049820-b5d8ea80-c1fd-11ea-984c-397afdd291b6.png)

**Hosted or self hosted?:**
- self-hosted
- latest master

**Additional context**

**Comment by 14MR** [comment]
Is it okay that there is almost no validation on this endpoint? If i skip timestamp, it doesn't try to insert the value even the response is 200.

**Comment by timgl** [comment]
Timestamp is not a required field, if it's not set it will default to current server time

**Comment by 14MR** [comment]
Unfortunately, it doesn't, because there is an error in parsing of the date.

```
web_1     | Internal Server Error: /capture/
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
web_1     |     response = get_response(request)
web_1     |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
web_1     |     response = self.process_exception_by_middleware(e, request)
web_1     |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
web_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1     |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
web_1     |     return view_func(*args, **kwargs)
web_1     |   File "/code/posthog/api/capture.py", line 168, in get_event
web_1     |     process_event(
web_1     |   File "/usr/local/lib/python3.8/site-packages/celery/local.py", line 191, in __call__
web_1     |     return self._get_current_object()(*a, **kw)
web_1     |   File "/usr/local/lib/python3.8/site-packages/celery/app/task.py", line 392, in __call__
web_1     |     return self.run(*args, **kwargs)
web_1     |   File "/code/posthog/tasks/process_event.py", line 197, in process_event
web_1     |     timestamp=_handle_timestamp(data, now, sent_at),
web_1     |   File "/code/posthog/tasks/process_event.py", line 167, in _handle_timestamp
web_1     |     now_datetime = parser.isoparse(now)
web_1     |   File "/usr/local/lib/python3.8/site-packages/dateutil/parser/isoparser.py", line 37, in func
web_1     |     return f(self, str_in, *args, **kwargs)
web_1     |   File "/usr/local/lib/python3.8/site-packages/dateutil/parser/isoparser.py", line 134, in isoparse
web_1     |     components, pos = self._parse_isodate(dt_str)
web_1     |   File "/usr/local/lib/python3.8/site-packages/dateutil/parser/isoparser.py", line 208, in _parse_isodate
web_1     |     return self._parse_isodate_common(dt_str)
web_1     |   File "/usr/local/lib/python3.8/site-packages/dateutil/parser/isoparser.py", line 213, in _parse_isodate_common
web_1     |     len_str = len(dt_str)
web_1     | TypeError: object of type 'datetime.datetime' has no len()
web_1     | [09/Jul/2020 14:17:11] "POST /capture/ HTTP/1.1" 500 105834
web_1     | [09/Jul/2020 14:17:16] "GET /api/event/actions/?properties=%
```
