### ISSUE TITLE
Async server running scheduled tasks crashes regularly

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#11982]
I've finally gotten to the bottom of what's truly causing the issue of async server restarts on Cloud: scheduled tasks (probably the last remaining service from the original plugin server from 2 years ago we haven't refactored). 

The server that's got the lock and is thus assigned to process tasks essentially gets "overloaded" (vague term) and crashes. It's still unclear to me whether this is an issue with memory, CPU, or something else (like Piscina crashing because of a queue that's too long). We've previously seen a benefit from reducing the number of concurrent partitions consumed from but that'd affect all of the above. I came back to my laptop just to confirm this hypothesis (it's 8pm) so will dig tomorrow.

<img width="730" alt="Screenshot 2022-09-26 at 20 05 35" src="https://user-images.githubusercontent.com/38760734/192396167-bc7f66e7-7476-4619-b15f-033643b055d7.png">

The way I've narrowed this down is two-fold - I looked at a ton of logs of crashed pods (like I've been doing for a long time) trying to find anything in common. I was struggling to get anywhere but then suddenly noticed the server that acquired the lock seemed to always be the one going down. I then pushed #11978 and saw that this is what a crash looks like every time:

```shell
# 100s of lines like below...
{"level":"info","time":1664232480118,"pid":67,"hostname":"posthog-plugins-async-59984c5b55-bpusx","msg":"(ASYNC) ⏲️ Running runEveryMinute for plugin config with ID 6055"}
{"level":"info","time":1664232480118,"pid":67,"hostname":"posthog-plugins-async-59984c5b55-bpusx","msg":"(ASYNC) ⏲️ Running runEveryMinute for plugin config with ID 7020"}
{"level":"info","time":1664232480118,"pid":67,"hostname":"posthog-plugins-async-59984c5b55-bpusx","msg":"(ASYNC) ⏲️ Running runEveryMinute for plugin config with ID 5161"}
{"level":"info","time":1664232480118,"pid":67,"hostname":"posthog-plugins-async-59984c5b55-bpusx","msg":"(ASYNC) ⏲️ Running runEveryMinute for plugin config with ID 12974"}
{"level":"info","time":1664232480118,"pid":67,"hostname":"posthog-plugins-async-59984c5b55-bpusx","msg":"(ASYNC) ⏲️ Running runEveryMinute for plugin config with ID 7872"}
{"level":"info","time":1664232480118,"pid":67,"hostname":"posthog-plugins-async-59984c5b55-bpusx","msg":"(ASYNC) ⏲️ Running runEveryMinute for plugin config with ID 12880"}
{"level":"info","time":1664232480118,"pid":67,"hostname":"posthog-plugins-async-59984c5b55-bpusx","msg":"(ASYNC) ⏲️ Running runEveryMinute for plugin config with ID 4968"}
{"level":"info","time":1664232480118,"pid":67,"hostname":"posthog-plugins-async-59984c5b55-bpusx","msg":"(ASYNC) ⏲️ Running runEveryMinute for plugin config with ID 5072"}
{"level":"info","time":1664232480118,"pid":67,"hostname":"posthog-plugins-async-59984c5b55-bpusx","msg":"(ASYNC) ⏲️ Running runEveryMinute for plugin config with ID 10652"}
{"level":"info","time":1664232480118,"pid":67,"hostname":"posthog-plugins-async-59984c5b55-bpusx","msg":"(ASYNC) ⏲️ Running runEveryMinute for plugin config with ID 9041"}
{"level":"info","time":1664232480118,"pid":67,"hostname":"posthog-plugins-async-59984c5b55-bpusx","msg":"(ASYNC) ⏲️ Running runEveryMinute for plugin config with ID 9927"}
{"level":"info","time":1664232480118,"pid":67,"hostname":"posthog-plugins-async-59984c5b55-bpusx","msg":"(ASYNC) ⏲️ Running runEveryMinute for plugin config with ID 9137"}
[core] INFO: Worker connected and looking for jobs... (task names: 'pluginJob')
[worker(worker-715fe7bf3815ec3b11)] INFO: Completed task 189334732 (pluginJob) with success (512.97ms)
[worker(worker-715fe7bf3815ec3b11)] INFO: Completed task 189334853 (pluginJob) with success (2216.54ms)
[worker(worker-715fe7bf3815ec3b11)] INFO: Completed task 189335010 (pluginJob) with success (513.69ms)
[worker(worker-f52ba6e3df43cd3fd7)] INFO: Completed task 189334553 (pluginJob) with success (14161.13ms)
AssertionError [ERR_ASSERTION]: nudge called after worker terminated
    at Object.nudge (/code/plugin-server/node_modules/graphile-worker/dist/worker.js:48:9)
    at /code/plugin-server/node_modules/graphile-worker/dist/main.js:203:49
    at Array.some (<anonymous>)
    at Client.handleNotification (/code/plugin-server/node_modules/graphile-worker/dist/main.js:203:25)
    at Client.emit (node:events:513:28)
    at Client.emit (node:domain:489:12)
    at Client._handleNotification (/code/plugin-server/node_modules/pg/lib/client.js:381:10)
    at Connection.emit (node:events:513:28)
    at Connection.emit (node:domain:489:12)
    at /code/plugin-server/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/code/plugin-server/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/code/plugin-server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
```

I also set up a plugin to run every minute and noticed it's quite erratic (skipped :15, :16, :17):

<img width="1263" alt="Screenshot 2022-09-26 at 17 19 20" src="https://user-images.githubusercontent.com/38760734/192396704-e9438e6f-2f41-4367-8b7a-ddaae4f7b209.png">

So yeah, scheduled tasks are the issue. Just documenting for now, will think about the optimal solution tomorrow.

**Comment by hazzadous** [comment]
Is great to have made some progress on this one! Such a head scratcher 🤔 

happy to help on a solution

**Comment by yakkomajuri** [comment]
Update - see how things are very erratic:

<img width="1452" alt="Screenshot 2022-09-27 at 11 24 26" src="https://user-images.githubusercontent.com/38760734/192553295-021a437b-c6fe-4874-9c8f-146e6f33e05e.png">
