### ISSUE TITLE
Screen recordings page: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by fdaugs** [PostHog/posthog#12856]
## Bug description

I upgraded my self hosted instance from 1.40.0 to 1.41.0 and now the screen recordings page shows the following error:

```
TypeError (ID 3d71bb553a6d47d3906e2bcf80004ccc)
Cannot convert undefined or null to object
```

This error is printed to the console:

```
instrument.ts:123 
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at e8 (PlayerMeta.tsx:165:33)
    at Aq (react-dom.production.min.js:153:146)
    at Xle (react-dom.production.min.js:261:496)
    at Yle (react-dom.production.min.js:246:265)
    at _$e (react-dom.production.min.js:246:194)
    at GV (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at Hr.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Um (react-dom.production.min.js:122:325)
    at hle (react-dom.production.min.js:123:61)
    at Pc (react-dom.production.min.js:122:496)
    at jm (react-dom.production.min.js:230:156)
    at Rle (react-dom.production.min.js:163:512)
    at index.cjs.js:439:263
    at s (index.cjs.js:761:11)
    at d (redux.js:305:7)
    at index.ts:51:26
    at index.ts:71:26
    at Object.dispatch (index.cjs.js:1768:28)
    at t.actions.<computed> [as getSessionRecordingsSuccess] (index.cjs.js:1150:28)
    at index.ts:150:45
```

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, 1.41.0

**Comment by fdaugs** [comment]
Update: Re-Login solved the Problem.
