### ISSUE TITLE
Table default.infi_clickhouse_orm_migrations doesn't exist. (UNKNOWN_TABLE) (version 22.3.15.33

### ISSUE THREAD

**Issue by kapil371** [PostHog/posthog#13524]
## Bug description
`Traceback (most recent call last):
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 362, in _get_applied_migrations_and_create_tables
    return self._get_applied_migrations(migrations_package_name, replicated)
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 379, in _get_applied_migrations
    return set(obj.module_name for obj in self.select(query))
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 379, in <genexpr>
    return set(obj.module_name for obj in self.select(query))
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 276, in select
    r = self._send(query, settings, True)
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 389, in _send
    raise ServerError(r.text)
infi.clickhouse_orm.database.ServerError: Code: 60. DB::Exception: Table default.infi_clickhouse_orm_migrations doesn't exist. (UNKNOWN_TABLE) (version 22.3.15.33 (official build))
 (0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/dell/Projects/posthog-code/posthog/management/commands/migrate_clickhouse.py", line 42, in handle
    self.migrate(CLICKHOUSE_HTTP_URL, options)
  File "/home/dell/Projects/posthog-code/posthog/management/commands/migrate_clickhouse.py", line 80, in migrate
    database.migrate(MIGRATIONS_PACKAGE_NAME, options["upto"], replicated=CLICKHOUSE_REPLICATION)
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 346, in migrate
    applied_migrations = self._get_applied_migrations_and_create_tables(migrations_package_name, replicated=replicated)
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 371, in _get_applied_migrations_and_create_tables
    return self._get_applied_migrations_and_create_tables(migrations_package_name, replicated, allow_missing_tables=False)
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 359, in _get_applied_migrations_and_create_tables
    return self._get_applied_migrations(migrations_package_name, replicated)
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 379, in _get_applied_migrations
    return set(obj.module_name for obj in self.select(query))
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 379, in <genexpr>
    return set(obj.module_name for obj in self.select(query))
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 276, in select
    r = self._send(query, settings, True)
  File "/home/dell/Projects/posthog-code/env/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 389, in _send
    raise ServerError(r.text)
infi.clickhouse_orm.database.ServerError: Code: 60. DB::Exception: Table default.infi_clickhouse_orm_migrations doesn't exist. (UNKNOWN_TABLE) (version 22.3.15.33 (official build))
  
![image](https://user-images.githubusercontent.com/83573750/210081519-768ea92b-635b-4657-9013-7d8cbaacd86d.png)

## How to reproduce

1. we followed these steps: https://posthog.com/handbook/engineering/developing-locally

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: please provide

**Comment by kappa90** [comment]
Seems related to https://github.com/PostHog/posthog/issues/11127

Is this a fresh install? Or did you try to update from a previous version?

Which version are you running?

If it's a fresh install, would you be able to follow the docs again and repeat the process step by step?

**Comment by kapil371** [comment]
yes its a fresh install and I repeated the steps many times

**Comment by kapil371** [comment]
It got fixed when I deleted all the dependent images like postgres, clickhouse, kafka etc but now again i am getting same error

**Comment by dgo2dance** [comment]
> It got fixed when I deleted all the dependent images like postgres, clickhouse, kafka etc but now again i am getting same error

Did you find a solution later? I also encountered the same error

**Comment by kapil371** [comment]
try to delete ZooKeeper and clickhouse images
