### ISSUE TITLE
When click insight events the error has occurred. Maybe I created event 26 over.

### ISSUE THREAD

**Issue by yoshiki-0428** [PostHog/posthog#13962]
## Bug description

When click insight events the error has occurred. Maybe I created event 26 over.

```
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at https://app-static-prod.posthog.com/static/chunk-UQYO3L5P.js:78:119804
    at Array.map (<anonymous>)
    at i4 (https://app-static-prod.posthog.com/static/chunk-UQYO3L5P.js:78:119438)
    at Vi (https://app-static-prod.posthog.com/static/InsightScene-AYXT7LK6.js:1:37916)
    at LP (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:2:49913)
    at B5 (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:2:58804)
    at _V (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:4:9097)
    at yV (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:4:858)
    at vve (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:4:781)
    at Y5 (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:2:85914)
    at https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:2:37219
    at rr.unstable_runWithPriority (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:1:11562)
    at Nc (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:2:36928)
    at HF (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:2:37165)
    at Xs (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:2:37100)
    at DD (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:4:18376)
    at ume (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:2:14514)
    at HTMLDocument.n (https://app-static-prod.posthog.com/static/chunk-QIRUHTQ5.js:153:1359)

```

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

https://user-images.githubusercontent.com/20635620/215128930-5b63eaa5-3b40-416b-9e0f-2f13fcc62156.mov

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by pjhul** [comment]
Hi @yoshiki-0428!

Thanks for the bug report! Definitely looks like we didn't expect to run out of letters in the alphabet 😆

I'll work on a fix for this right now.
