### ISSUE TITLE
React Error Attempting to Edit 'Website Users by Location' default insight

### ISSUE THREAD

**Issue by feebleone** [PostHog/posthog#14346]
On PostHog cloud Dashboards (or Insights), when you attempt to edit or select the 'Website Users by Location', a react error is thrown.

![image](https://user-images.githubusercontent.com/43376760/220406534-4310195e-9529-497c-9bbb-2af6329a4239.png)

Yields
```
Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=_k for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:2:48402
    at Fi (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:2:57800)
    at EV (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:4:8606)
    at CV (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:4:858)
    at _ve (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:4:781)
    at X5 (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:2:85914)
    at https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:2:37219
    at rr.unstable_runWithPriority (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:1:11562)
    at Nc (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:2:36928)
    at $F (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:2:37165)
    at Xs (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:2:37100)
    at Rc (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:2:82670)
    at ZF (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:2:54274)
    at https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:5:4427
    at s (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:5:7239)
    at Object.d [as dispatch] (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:4:23266)
    at e (<anonymous>:1:37227)
    at https://app-static-prod.posthog.com/static/chunk-M4F5WCNY.js:1:8824
    at https://app-static-prod.posthog.com/static/chunk-AFOQASK2.js:1:1459
    at Object.dispatch (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:5:21084)
    at Object.dispatch (<anonymous>:1:55003)
    at t.actions.<computed> [as setScene] (https://app-static-prod.posthog.com/static/chunk-TJPH6XP2.js:5:11717)
    at loadScene (https://app-static-prod.posthog.com/static/chunk-Q4OWXYAV.js:5:32711)
```

*Links:* 
Example Page where screen shot was taken: https://app.posthog.com/dashboard/62518
Page where error occurs: https://app.posthog.com/insights/vISeHxhh/edit

## How to reproduce

1. In PostHog Cloud, create a new dashboard
2. Choose template Website Traffic.
3. On the default insight 'Website Users by location', click the ellipses, then select 'Edit' to present the error. (See screenshot)
4. Replace step 3 by clicking on the 'Website Users by location' title to give the same error.

## Environment
PostHog Cloud US project ID: 19840

**Comment by raquelmsmith** [comment]
Thanks for reporting @feebleone. I'm hoping the PR I just linked here fixes it.
