### ISSUE TITLE
Error running migration 0039_person_overrides_dict

### ISSUE THREAD

**Issue by jredl-va** [PostHog/posthog#14552]
## Bug description

There looks to be a bug within the script `0039_person_overrides_dict`: https://github.com/PostHog/posthog/blob/master/posthog/models/person_overrides/sql.py#L163

Reviewing other migrating scripts they all use `CREATE IF NOT EXISTS` as create or replace isn't necessarily supported by the underlying clickhouse db. 

```
{"event": "Skipping async migrations setup. This is unsafe in production!", "timestamp": "2023-03-04T03:08:24.247764Z", "logger": "posthog.apps", "level": "warning", "pid": 25, "tid": 139674347661120}
{"event": "AXES: BEGIN LOG", "timestamp": "2023-03-04T03:08:24.252054Z", "logger": "axes.apps", "level": "info", "pid": 25, "tid": 139674347661120}
{"event": "AXES: Using django-axes version 5.9.0", "timestamp": "2023-03-04T03:08:24.252584Z", "logger": "axes.apps", "level": "info", "pid": 25, "tid": 139674347661120}
{"event": "AXES: blocking by IP only.", "timestamp": "2023-03-04T03:08:24.252717Z", "logger": "axes.apps", "level": "info", "pid": 25, "tid": 139674347661120}
Operations to perform:
  Apply all migrations: admin, auth, axes, contenttypes, ee, otp_static, otp_totp, posthog, sessions, social_django, two_factor
Running migrations:
  No migrations to apply.
{"event": "Skipping async migrations setup. This is unsafe in production!", "timestamp": "2023-03-04T03:08:28.770332Z", "logger": "posthog.apps", "level": "warning", "pid": 41, "tid": 140561754949440}
{"event": "AXES: BEGIN LOG", "timestamp": "2023-03-04T03:08:28.774365Z", "logger": "axes.apps", "level": "info", "pid": 41, "tid": 140561754949440}
{"event": "AXES: Using django-axes version 5.9.0", "timestamp": "2023-03-04T03:08:28.774809Z", "logger": "axes.apps", "level": "info", "pid": 41, "tid": 140561754949440}
{"event": "AXES: blocking by IP only.", "timestamp": "2023-03-04T03:08:28.774937Z", "logger": "axes.apps", "level": "info", "pid": 41, "tid": 140561754949440}
{"event": "Applying migration 0039_person_overrides_dict...", "timestamp": "2023-03-04T03:08:29.868153Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 140561754949440}
{"event": "    Executing python operation run_sql", "timestamp": "2023-03-04T03:08:29.868314Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 140561754949440}
Traceback (most recent call last):
  File "/code/posthog/clickhouse/client/execute.py", line 100, in sync_execute
    result = client.execute(
  File "/python-runtime/clickhouse_driver/client.py", line 267, in execute
    rv = self.process_ordinary_query(
  File "/python-runtime/clickhouse_driver/client.py", line 453, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/python-runtime/clickhouse_driver/client.py", line 117, in receive_result
    return result.get_result()
  File "/python-runtime/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/python-runtime/clickhouse_driver/client.py", line 133, in packet_generator
    packet = self.receive_packet()
  File "/python-runtime/clickhouse_driver/client.py", line 150, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 80.
DB::Exception: There was an error on [chi-posthog-posthog-0-0:9000]: Code: 80. DB::Exception: CREATE OR REPLACE TABLE query is supported only for Atomic databases. (INCORRECT_QUERY) (version 22.8.11.15 (official build)). Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3f9b5a in /usr/bin/clickhouse
1. DB::DDLQueryStatusSource::generate() @ 0x1518de2e in /usr/bin/clickhouse
2. DB::ISource::tryGenerate() @ 0x15cdced5 in /usr/bin/clickhouse
3. DB::ISource::work() @ 0x15cdca26 in /usr/bin/clickhouse
4. DB::ExecutionThreadContext::executeTask() @ 0x15cf94aa in /usr/bin/clickhouse
5. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15ceda1b in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x15cec979 in /usr/bin/clickhouse
7. DB::PipelineExecutor::execute(unsigned long) @ 0x15cec77d in /usr/bin/clickhouse
8. ? @ 0x15cfcf29 in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4bb6a8 in /usr/bin/clickhouse
10. ? @ 0xa4be8bd in /usr/bin/clickhouse
11. ? @ 0x7f9b647a3609 in ?
12. clone @ 0x7f9b646c8133 in ?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/manage.py", line 21, in <module>
    main()
  File "/code/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/python-runtime/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/python-runtime/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/python-runtime/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/python-runtime/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/code/posthog/management/commands/migrate_clickhouse.py", line 36, in handle
    self.migrate(CLICKHOUSE_HTTP_URL, options)
  File "/code/posthog/management/commands/migrate_clickhouse.py", line 74, in migrate
    database.migrate(MIGRATIONS_PACKAGE_NAME, options["upto"], replicated=True)
  File "/python-runtime/infi/clickhouse_orm/database.py", line 352, in migrate
    operation.apply(self)
  File "/python-runtime/infi/clickhouse_orm/migrations.py", line 250, in apply
    self._func(database)
  File "/code/posthog/clickhouse/client/migration_tools.py", line 12, in run_sql
    sync_execute(sql)
  File "/code/posthog/utils.py", line 1225, in inner
    return inner._impl(*args, **kwargs)  # type: ignore
  File "/code/posthog/clickhouse/client/execute.py", line 111, in sync_execute
    raise err
posthog.errors.CHQueryErrorIncorrectQuery: Code: 80.
DB::Exception: There was an error on [chi-posthog-posthog-0-0:9000]: Code: 80. DB::Exception: CREATE OR REPLACE TABLE query is supported only for Atomic databases. (INCORRECT_QUERY) (version 22.8.11.15 (official build)). Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3f9b5a in /usr/bin/clickhouse
1. DB::DDLQueryStatusSource::generate() @ 0x1518de2e in /usr/bin/clickhouse
2. DB::ISource::tryGenerate() @ 0x15cdced5 in /usr/bin/clickhouse
3. DB::ISource::work() @ 0x15cdca26 in /usr/bin/clickhouse
4. DB::ExecutionThreadContext::executeTask() @ 0x15cf94aa in /usr/bin/clickhouse
5. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15ceda1b in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x15cec979 in /usr/bin/clickhouse
7. DB::PipelineExecutor::execute(unsigned long) @ 0x15cec77d in /usr/bin/clickhouse
8. ? @ 0x15cfcf29 in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4bb6a8 in /usr/bin/clickhouse
10. ? @ 0xa4be8bd in /usr/bin/clickhouse
11. ? @ 0x7f9b647a3609 in ?
12. clone @ 0x7f9b646c8133 in ?
```

Would you accept a PR if I updated this script to use use a simple CREATE command?

**Comment by voarsh2** [comment]
Yes, I basically reverted the bad commit........
https://github.com/PostHog/posthog/commit/18c27227f7d9f2dfbc5ed95ada4ea3b3d8b27822
https://github.com/PostHog/posthog/pull/13977


Seems Posthog is giving up making any releases, even for Docker-Compose.... not been any new release since 1.43...

**Comment by hazzadous** [comment]
Ah interesting. @voarsh2 those commits _should_ have been to ensure that we're not failing silently with ClickHouse migrations. By reverting those commits you'll still hit the error but it will not complain.

As @jredl-va mentions, this is an issue with the type of ClickHouse database not supporting the `CREATE OR REPLACE FUNCTION`. See [this list of database variants](https://clickhouse.com/docs/en/engines/database-engines/) for details. They all have slightly different characteristics. It should default for the `Atomic` type, which should work with this command.

@jredl-va mind sharing details of your setup? And how the ClickHouse database was created?

> Would you accept a PR if I updated this script to use use a simple CREATE command?

Yes that would work I think, I would want to ensure that the migration is retriable. We can't make it atomic, but at least we can ensure that if it fails the first time for some reason, then it manages to push the migration through the second time without issues. I would also however want to understand how you have a different database type before we merge anything.

I'll tag @tomasfarias to see if he has a way of applying the migration.

**Comment by hazzadous** [comment]
Oh and to get the database type, you can run `select * from system.databases` via e.g. `clickhouse-client`

**Comment by voarsh2** [comment]
> Ah interesting. @voarsh2 those commits _should_ have been to ensure that we're not failing silently with ClickHouse migrations. By reverting those commits you'll still hit the error but it will not complain.

Oops. My bad. So how did this troublesome commit get passed your tests (as in pass)?

> Oh and to get the database type, you can run select * from system.databases via e.g. clickhouse-client



This is my output:

```
SELECT *
FROM system.databases

Query id: 70488350-ddea-467e-9492-9d66579af360

┌─name───────────────┬─engine───┬─data_path─────────────────────────┬─metadata_path───────────────────────────────────────────────────────┬─uuid─────────────────────────────────┬─comment─┐
│ INFORMATION_SCHEMA │ Memory   │ /var/lib/clickhouse/              │                                                                     │ 00000000-0000-0000-0000-000000000000 │         │
│ information_schema │ Memory   │ /var/lib/clickhouse/              │                                                                     │ 00000000-0000-0000-0000-000000000000 │         │
│ posthog            │ Ordinary │ /var/lib/clickhouse/data/posthog/ │ /var/lib/clickhouse/metadata/posthog/                               │ 00000000-0000-0000-0000-000000000000 │         │
│ system             │ Atomic   │ /var/lib/clickhouse/store/        │ /var/lib/clickhouse/store/d59/d597a02b-1de1-4f81-bf2d-adea1e75af10/ │ d597a02b-1de1-4f81-bf2d-adea1e75af10 │         │
└────────────────────┴──────────┴───────────────────────────────────┴─────────────────────────────────────────────────────────────────────┴──────────────────────────────────────┴─────────┘

4 rows in set. Elapsed: 0.002 sec. 
```

So, if I reverted the commits, and supposedly completed the migration, in Async Migrations there's no way to re-do this migration....?

**Comment by hazzadous** [comment]
> Oops. My bad. So how did this troublesome commit get passed your tests (as in pass)?

In CI we are likely defaulting to Atomic database type, which means it was all fine.

From your output it looks like it's somehow an Ordinary type. Possibly something like ClickHouse has changed the default, but previously it was using Ordinary as in your setup. We'll need either a strategy to ensure that we can handle either supporting the Ordinary database type or converting it. What do you think @fuziontech is converting something we can do?

**Comment by hazzadous** [comment]
> So, if I reverted the commits, and supposedly completed the migration, in Async Migrations there's no way to re-do this migration....?

And yes, they will be marked as complete, but not really, so you'd have to remove the entry in the migrations table that says "I've run these migrations"

**Comment by hazzadous** [comment]
For what it's worth there is some detail [here](https://kb.altinity.com/engines/altinity-kb-atomic-database-engine/how-to-convert-ordinary-to-atomic/) on converting the database type.

And also details [here](https://kb.altinity.com/engines/altinity-kb-atomic-database-engine/) on when the switch was made to default to Atomic 😅

**Comment by hazzadous** [comment]
@jredl-va @voarsh2 I've pushed up https://github.com/PostHog/posthog/pull/14640 as you mention @jredl-va we use if not exists with success elsewhere and that should be enough in this case.

I'm going to punt on the conversion to `Atomic` database type for now 🙄

**Comment by hazzadous** [comment]
@jredl-va @voarsh2 that's merged in now, so fingers crossed when the new docker image is out you should be good to go. That will be when https://github.com/PostHog/posthog/actions/runs/4372839327/jobs/7650258100 is done.

**Comment by jredl-va** [comment]
@hazzadous thanks so much! Just getting caught up on this thread (will try updating again this afternoon). 

Let me know if you would like me to provide any further information on our clickhouse setup. Note, that we are planning to migrate to posthog cloud but we would still like to keep up to date with the posthog releases until that migration has completed.

**Comment by jredl-va** [comment]
With that change to the script it was able to run to completion this time around!

```
  Apply all migrations: admin, auth, axes, contenttypes, ee, otp_static, otp_totp, posthog, sessions, social_django, two_factor
Running migrations:
  Applying posthog.0307_pluginconfig_admin... OK
  Applying posthog.0308_add_indirect_person_override_constraints... OK
{"event": "Skipping async migrations setup. This is unsafe in production!", "timestamp": "2023-03-10T18:42:57.443137Z", "logger": "posthog.apps", "level": "warning", "pid": 41, "tid": 139694611830592}
{"event": "AXES: BEGIN LOG", "timestamp": "2023-03-10T18:42:57.448109Z", "logger": "axes.apps", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "AXES: Using django-axes version 5.9.0", "timestamp": "2023-03-10T18:42:57.448731Z", "logger": "axes.apps", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "AXES: blocking by IP only.", "timestamp": "2023-03-10T18:42:57.448947Z", "logger": "axes.apps", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "Applying migration 0039_person_overrides_dict...", "timestamp": "2023-03-10T18:42:58.777582Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "    Executing python operation run_sql", "timestamp": "2023-03-10T18:42:58.777750Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "Applying migration 0040_add_ttl_to_performance_events...", "timestamp": "2023-03-10T18:42:58.925899Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "    Executing python operation update_performance_events_ttl", "timestamp": "2023-03-10T18:42:58.926090Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "Applying migration 0041_kafka_partitions_stats...", "timestamp": "2023-03-10T18:42:59.057301Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "    Executing python operation run_sql", "timestamp": "2023-03-10T18:42:59.057498Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "    Executing python operation run_sql", "timestamp": "2023-03-10T18:42:59.192793Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "    Executing python operation run_sql", "timestamp": "2023-03-10T18:42:59.477057Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "Applying migration 0042_kafka_partitions_stats...", "timestamp": "2023-03-10T18:42:59.617543Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "    Executing python operation run_sql", "timestamp": "2023-03-10T18:42:59.617778Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "    Executing python operation run_sql", "timestamp": "2023-03-10T18:42:59.748625Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "    Executing python operation run_sql", "timestamp": "2023-03-10T18:42:59.894934Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
{"event": "    Executing python operation run_sql", "timestamp": "2023-03-10T18:43:00.031070Z", "logger": "migrations", "level": "info", "pid": 41, "tid": 139694611830592}
✅ Migration successful
```

**Comment by hazzadous** [comment]
Nice!

Yeah it's interesting that it's the Ordinary ClickHouse database type. Would love to understand why that might be the case, in case it's relevant to others or if we need to change something with the setup to ensure it always uses Atomic.
