### ISSUE TITLE
Error "[KEA] Can not find path "scenes.insights.insightLogic.new" in the store"

### ISSUE THREAD

**Issue by 4ian** [PostHog/posthog#14706]
## Bug description

When trying to refresh a dashboard, we get a crash:

```
Error: [KEA] Can not find path "scenes.insights.insightLogic.new" in the store.
    at https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:19447
    at Array.reduce (<anonymous>)
    at $he (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:19398)
    at e.selector (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:17310)
    at https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:4:28051
    at Object.c [as filters] (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:4:26513)
    at Object.get [as filters] (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:14308)
    at https://app-static-prod.posthog.com/static/chunk-LP2UYXIY.js:37:121254
    at https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:17387
    at V_ (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:22980)
    at Uhe (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:24702)
    at Ghe.t.build (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:26007)
    at r (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:25873)
    at wd (https://app-static-prod.posthog.com/static/chunk-LP2UYXIY.js:37:122599)
    at q6 (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:2:49913)
    at MV (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:4:8176)
    at OV (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:4:858)
    at Lve (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:4:781)
    at i6 (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:2:85914)
    at https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:2:37219
    at rr.unstable_runWithPriority (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:1:11562)
    at Sc (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:2:36928)
    at ZF (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:2:37165)
    at Qs (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:2:37100)
    at Cc (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:2:82670)
    at uV (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:2:54274)
    at https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:4427
    at s (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:7239)
    at d (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:4:23266)
    at https://app-static-prod.posthog.com/static/chunk-LP2UYXIY.js:1:8959
    at https://app-static-prod.posthog.com/static/chunk-UTCODKD3.js:1:1459
    at Object.dispatch (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:21084)
    at t.actions.<computed> [as markInsightTimedOut] (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:5:11717)
    at https://app-static-prod.posthog.com/static/chunk-LP2UYXIY.js:124:95310
    at n (https://app-static-prod.posthog.com/static/chunk-JQMFGAUO.js:153:1359)
```

## How to reproduce

1. Open https://app.posthog.com/dashboard/43088
2. Refresh the graphs
3. Crash (`ID da6fb70157a54915a5a0481afa705eb2`)

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/1280130/224666951-8168615a-bc42-4a79-b139-61c7d37f2f81.png">

## Environment

- [x] PostHog Cloud US, project ID: 8326
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context

Happened on other dashboard too

**Comment by hazzadous** [comment]
I'll check in with the appropriate team here, but as a temporary workaround, have you tried clearing your browser cache and local storage?

**Comment by pauldambra** [comment]
Hey @4ian 👋 

We merged https://github.com/PostHog/posthog/pull/14723 which I believe fixes this. 

I'll close this issue but feel free to re-open if it isn't fixed for you!
