### ISSUE TITLE
Self-Hosted Deployment intermittently stops displaying new events

### ISSUE THREAD

**Issue by cooldracula** [PostHog/posthog#15376]
## Bug description

Intermittently, our posthog deployment stops showing new logs.  Graphs on our site will show info up to a particular day.
Previoiusly , running `docker-compose restart` fixed the issue.  Visiting the page after we saw events for the missing period, indicating that Posthog was still recording events, but the information was not being passed to the website.

This has happened three times since our first deployment on 29 March.

The most recent time, restarting the containers did not fix the issue and we are still not show events for the last day.

## How to reproduce

1. Deploy Hobby Self-Hosted to an appropriate machine with:
  ```
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)"
  ```
2. After period of time, check dashboard and see steep decline in all graphs, as new events are not showing.
3. On server, run `docker ps` and confirm all containers are running, though some may have restarted since first creation.
4. run `docker-compose restart`
5. visit dashboard when available again, graphs have corrected with missing time period 
5a.  Or, visit dashboard, and see new events are still not showing.

(Apologies for the vagueness of the reproducibility.  This has happened three times in our deployment, but I can not find a pattern for when the metrics stopped appearing, or how to trigger this happening.)

## Environment

- PostHog Hobby Self Hosted, deployed to a digital ocean droplet (Ubuntu 22/4gb Memory/ 80gb diskspace).
- Originally deployed on 29 March, using the command, and so bin/hobby would've been at commit 6f39b68dd2bbe535ac5d661584fcfcc8970fd24c, i believe.
  
-  The digest hashes for each image are:

| container name | digest hash |
| -------------- | ----------- |
| admin-zookeeper-1 |  04ec824d47af1b3be5327cd3f852fe6c9b565df80ad006612dc52d8ce286f2e0 |
| admin-plugins-1 |  9261c4111daa98959572dec7cf4f656f4def19146d66176699d348da7ff8988a |
| admin-caddy-1 |  181f13e1cc5fd90d0b4869e57689b5200589ca1029971fc7233082c04806a55b |
| admin-worker-1 |   9261c4111daa98959572dec7cf4f656f4def19146d66176699d348da7ff8988a |
| admin-web-1 |   9261c4111daa98959572dec7cf4f656f4def19146d66176699d348da7ff8988a |
| admin-clickhouse-1 |   61e4bd87b5d286a5573ede6493b0bde4fa8cde03d672c8bb66aa6893d09a3294 |
| admin-kafka-1 |   7ece89314f5cd07884f7bf1342c1fa539fd4a80a5e53b33265b32e38ed84890f |
| admin-object_storage-1 |   e1a47fe62a05ea1289b6314a0415d988fd7d377234d0482adcf47ec365aa7a53 |
| admin-db-1 |   0c2beca0db95561f945785909801f36e0825ad7da8eed514c70f79d4abecf363 |
| admin-redis-1 |   fd45e5a11a9d7583a57867f782459a9b04b4949a78bf13ab79b83017b4da2121 |

- I made small change to docker-compose file, adding the env var `ZOOKEEPER_AUTOPURGE_PURGEINTERVAL=12`
 
## Additional context
I left a similar comment in the post-hog slack #community channel.  If that's the more appropriate channel for reports like this, I'll close this issue and continue the conversation there.

Thank you!

**Comment by voarsh2** [comment]
How about checking logs in plugin container?

**Comment by cooldracula** [comment]
Ah, good idea, @voarsh2!  Looking through them, I noticed a pattern, though I'm not sure its cause, where the various servers become unresponsive giving ECONNREFUSED errors, which triggers a larger error in clickhouse, which then seems to cause the plugins server to restart.

Here is a dump of one of the instances:
```
{"level":"info","time":1684024615370,"pid":13,"hostname":"49b5acddd024","groupId":"scheduled-tasks-runner","offsets":{},"msg":"[MAIN] ℹ️ consumer_status"}
{"level":"info","time":1684024615370,"pid":13,"hostname":"49b5acddd024","groupId":"jobs-inserter","offsets":{},"msg":"[MAIN] ℹ️ consumer_status"}
{"level":"info","time":1684024615370,"pid":13,"hostname":"49b5acddd024","groupId":"ingester","offsets":{},"msg":"[MAIN] ℹ️ consumer_status"}
{"level":"ERROR","timestamp":"2023-05-14T00:36:56.013Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:36:56.027Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.20.0.6:9092","retryCount":0,"retryTime":335}
{"level":"ERROR","timestamp":"2023-05-14T00:36:56.027Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:36:56.040Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 172.20.0.6:9092","groupId":"clickhouse-ingestion","stack":"KafkaJSConnectionError: Connection error: connect ECONNREFUSED 172.20.0.6:9092\n    at Socket.onError (/code/plugin-server/node_modules/.pnpm/kafkajs@2.2.2/node_modules/kafkajs/src/network/connection.js:210:23)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"ERROR","timestamp":"2023-05-14T00:36:56.090Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:36:56.091Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 172.20.0.6:9092","groupId":"scheduled-tasks-runner","stack":"KafkaJSConnectionError: Connection error: connect ECONNREFUSED 172.20.0.6:9092\n    at Socket.onError (/code/plugin-server/node_modules/.pnpm/kafkajs@2.2.2/node_modules/kafkajs/src/network/connection.js:210:23)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}
{"level":"ERROR","timestamp":"2023-05-14T00:36:56.092Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:36:56.093Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.20.0.6:9092","retryCount":0,"retryTime":331}
{"level":"ERROR","timestamp":"2023-05-14T00:37:03.409Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:03.412Z","logger":"kafkajs","message":"[Consumer] Restarting the consumer in 300ms","retryTime":300,"groupId":"clickhouse-ingestion"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:03.412Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970"}
{"level":"info","time":1684024623410,"pid":13,"hostname":"49b5acddd024","groupId":"clickhouse-ingestion","offsets":{},"msg":"[MAIN] ℹ️ consumer_status"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:03.422Z","logger":"kafkajs","message":"[Consumer] Restarting the consumer in 300ms","retryTime":300,"groupId":"scheduled-tasks-runner"}
(node:13) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 61)
(Use `node --trace-warnings ...` to show where the warning was created)
{"level":"info","time":1684024623410,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 🛑 Kafka consumer disconnected!"}
{"level":"error","time":1684024623410,"pid":13,"hostname":"49b5acddd024","name":"KafkaJSConnectionError","retriable":true,"broker":"kafka:9092","code":"ECONNREFUSED","msg":"[MAIN] ⚠️ Kafka consumer group clickhouse-ingestion crashed:\n"}
{"level":"error","time":1684024623412,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] ⏲ Shutting plugin server down gracefully with SIGTERM..."}
{"level":"info","time":1684024623412,"pid":13,"hostname":"49b5acddd024","groupId":"scheduled-tasks-runner","offsets":{},"msg":"[MAIN] ℹ️ consumer_status"}
{"level":"info","time":1684024623412,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 🛑 Kafka consumer disconnected!"}
{"level":"error","time":1684024623412,"pid":13,"hostname":"49b5acddd024","name":"KafkaJSConnectionError","retriable":true,"broker":"kafka:9092","code":"ECONNREFUSED","msg":"[MAIN] ⚠️ Kafka consumer group scheduled-tasks-runner crashed:\n"}
{"level":"error","time":1684024623421,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] ⏲ Shutting plugin server down gracefully with SIGTERM..."}
{"level":"info","time":1684024623428,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 💤  Shutting down gracefully..."}
{"level":"info","time":1684024623437,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] ⏳ Stopping Kafka queue..."}
{"level":"info","time":1684024623441,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 🔄 Stopping Graphile worker..."}
{"level":"info","time":1684024623441,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 🔄 Stopping Graphile worker runner"}
{"level":"info","time":1684024623443,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] ⏹ Kafka consumer stopped!"}
{"level":"info","time":1684024623443,"pid":13,"hostname":"49b5acddd024","groupId":"scheduled-tasks-runner","offsets":{},"msg":"[MAIN] ℹ️ consumer_status"}
{"level":"info","time":1684024623443,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 🛑 Kafka consumer disconnected!"}
{"level":"info","time":1684024623443,"pid":13,"hostname":"49b5acddd024","groupId":"clickhouse-ingestion","offsets":{},"msg":"[MAIN] ℹ️ consumer_status"}
{"level":"info","time":1684024623443,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 🛑 Kafka consumer disconnected!"}
{"level":"info","time":1684024623446,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 💤  Shutting down gracefully..."}
{"level":"info","time":1684024623446,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] ⏳ Stopping Kafka queue..."}
{"level":"info","time":1684024623446,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 🔄 Stopping Graphile worker..."}
{"level":"info","time":1684024623446,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 🛑 Stopped Graphile worker..."}
{"level":"info","time":1684024623446,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] ⏹ Kafka consumer stopped!"}
{"level":"info","time":1684024623446,"pid":13,"hostname":"49b5acddd024","groupId":"scheduled-tasks-runner","offsets":{},"msg":"[MAIN] ℹ️ consumer_status"}
{"level":"info","time":1684024623446,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 🛑 Kafka consumer disconnected!"}
{"level":"info","time":1684024623446,"pid":13,"hostname":"49b5acddd024","groupId":"clickhouse-ingestion","offsets":{},"msg":"[MAIN] ℹ️ consumer_status"}
{"level":"info","time":1684024623446,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 🛑 Kafka consumer disconnected!"}
{"level":"info","time":1684024623453,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] 🛑 Pub-sub stopped for channels: reload-plugins, reset-available-features-cache, reload-action, drop-action"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:03.604Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:03.605Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":1,"retryTime":612}
{"level":"ERROR","timestamp":"2023-05-14T00:37:03.605Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:03.605Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":1,"retryTime":578}
{"level":"ERROR","timestamp":"2023-05-14T00:37:03.809Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:03.810Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.125Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.126Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":0,"retryTime":278}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.187Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.188Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.20.0.6:9092","retryCount":2,"retryTime":1130}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.225Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.225Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.20.0.6:9092","retryCount":2,"retryTime":1366}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.320Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.321Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.421Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.421Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.20.0.6:9092","retryCount":1,"retryTime":496}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.833Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.919Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:04.920Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.20.0.6:9092","retryCount":2,"retryTime":866}
{"level":"ERROR","timestamp":"2023-05-14T00:37:05.328Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:05.329Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.20.0.6:9092","retryCount":3,"retryTime":2036}
{"level":"info","time":1684024625370,"pid":13,"hostname":"49b5acddd024","groupId":"jobs-inserter","offsets":{},"msg":"[MAIN] ℹ️ consumer_status"}
{"level":"info","time":1684024625370,"pid":13,"hostname":"49b5acddd024","groupId":"ingester","offsets":{},"msg":"[MAIN] ℹ️ consumer_status"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:05.593Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:05.593Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.20.0.6:9092","retryCount":3,"retryTime":2584}
{"level":"ERROR","timestamp":"2023-05-14T00:37:05.788Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:05.788Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.20.0.6:9092","retryCount":3,"retryTime":1650}
{"level":"ERROR","timestamp":"2023-05-14T00:37:07.374Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:07.375Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.20.0.6:9092","retryCount":4,"retryTime":4650}
{"level":"ERROR","timestamp":"2023-05-14T00:37:07.441Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:07.442Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.20.0.6:9092","retryCount":4,"retryTime":2940}
{"level":"ERROR","timestamp":"2023-05-14T00:37:08.187Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 172.20.0.6:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-01881416-8620-0000-86d7-c37853612970","stack":"Error: connect ECONNREFUSED 172.20.0.6:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)"}
{"level":"ERROR","timestamp":"2023-05-14T00:37:08.188Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 172.20.0.6:9092","retryCount":4,"retryTime":5314}
{"level":"error","time":1684024628413,"pid":13,"hostname":"49b5acddd024","msg":"[MAIN] ⏲ Plugin server still running after 5 s, killing it forcefully!"}
2023-05-14T00:37:22.465555Z [warning  ] Failed to connect to clickhouse:9440 [clickhouse_driver.connection] pid=10 tid=139947957700416
Traceback (most recent call last):
  File "/python-runtime/clickhouse_driver/connection.py", line 318, in connect
    return self._init_connection(host, port)
  File "/python-runtime/clickhouse_driver/connection.py", line 282, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/python-runtime/clickhouse_driver/connection.py", line 254, in _create_socket
    raise err
  File "/python-runtime/clickhouse_driver/connection.py", line 245, in _create_socket
    sock.connect(sa)
  File "/usr/local/lib/python3.8/ssl.py", line 1342, in connect
    self._real_connect(addr, False)
  File "/usr/local/lib/python3.8/ssl.py", line 1329, in _real_connect
    super().connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/python-runtime/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/python-runtime/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/python-runtime/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/python-runtime/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/code/posthog/apps.py", line 52, in ready
    in_range, version = service_version_requirement.is_service_in_accepted_version()
  File "/code/posthog/version_requirement.py", line 28, in is_service_in_accepted_version
    service_version = self.get_service_version()
  File "/code/posthog/version_requirement.py", line 36, in get_service_version
    return get_clickhouse_version()
  File "/code/posthog/version_requirement.py", line 58, in get_clickhouse_version
    rows = client.execute("SELECT version()")
  File "/python-runtime/clickhouse_driver/client.py", line 252, in execute
    self.connection.force_connect()
  File "/python-runtime/clickhouse_driver/connection.py", line 212, in force_connect
    self.connect()
  File "/python-runtime/clickhouse_driver/connection.py", line 339, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. Connection refused (clickhouse:9440)
▶️ Starting plugin server...
```

Before and after this log is a steady repetition of those info level logs showing consumer status.  I am not quite sure what is happening though to trigger those server refusals.
