### ISSUE TITLE
ModuleNotFoundError: No module named 'ee'

### ISSUE THREAD

**Issue by Rcjuk** [PostHog/posthog#1638]
## Bug description

Deployed on AWS Fargate and i'm trying to boot up the latest copy of the image

## Expected behavior

It to work!

## How to reproduce

1. Try to deploy to Fargate
## Environment

- AWS Fargate via the docker image
- Latest

## Additional context

```2020-09-10 15:31:08from .api import api_not_found, capture, dashboard, decide, router, team, user
2020-09-10 15:31:08File "/code/posthog/api/capture.py", line 11, in <module>
2020-09-10 15:31:08from ee.clickhouse.process_event import process_event_ee # type: ignore
2020-09-10 15:31:08ModuleNotFoundError: No module named 'ee'
2020-09-10 15:31:08res = instance.__dict__[self.name] = self.func(instance)
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
2020-09-10 15:31:08return import_module(self.urlconf_name)
2020-09-10 15:31:08File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-09-10 15:31:08return _bootstrap._gcd_import(name[level:], package, level)
2020-09-10 15:31:08File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-09-10 15:31:08File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-09-10 15:31:08File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2020-09-10 15:31:08File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-09-10 15:31:08File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2020-09-10 15:31:08File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-09-10 15:31:08File "/code/posthog/urls.py", line 22, in <module>
2020-09-10 15:31:08return checks.run_checks(**kwargs)
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
2020-09-10 15:31:08new_errors = check(app_configs=app_configs)
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
2020-09-10 15:31:08return check_resolver(resolver)
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
2020-09-10 15:31:08return check_method()
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
2020-09-10 15:31:08for pattern in self.url_patterns:
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
2020-09-10 15:31:08res = instance.__dict__[self.name] = self.func(instance)
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
2020-09-10 15:31:08patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
2020-09-10 15:31:08self.fetch_command(subcommand).run_from_argv(self.argv)
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
2020-09-10 15:31:08self.execute(*args, **cmd_options)
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
2020-09-10 15:31:08self.check()
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
2020-09-10 15:31:08all_issues = self._run_checks(
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
2020-09-10 15:31:08issues.extend(super()._run_checks(**kwargs))
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
2020-09-10 15:31:08Traceback (most recent call last):
2020-09-10 15:31:08File "manage.py", line 21, in <module>
2020-09-10 15:31:08main()
2020-09-10 15:31:08File "manage.py", line 17, in main
2020-09-10 15:31:08execute_from_command_line(sys.argv)
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
2020-09-10 15:31:08utility.execute()
2020-09-10 15:31:08File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute```

#### *Thank you* for your bug report – we love squashing them!

**Comment by timgl** [comment]
Hi there! Are you using the posthog-foss image?

**Comment by Rcjuk** [comment]
```posthog/posthog:latest```

Looks like the latest.

**Comment by timgl** [comment]
@Rcjuk Could you try again? We've made a change to the docker image that should hopefully solve this

**Comment by Rcjuk** [comment]
Yes it did eventually boot ok. 👍 

You might need a `posthog/posthog:stable` ;)
