### ISSUE TITLE
Error when running posthog

### ISSUE THREAD

**Issue by oburd** [PostHog/posthog#16843]
Hello!
Can you tell me where is my error ? What i did wrong ?
There are a container
{'event': ['Skipping service version requirements. This is dangerous and PostHog might not work as expected!'], 'timestamp': '2023-07-31T14:17:58.660066Z', 'logger': 'posthog.settings.service_requirements', 'level': 'warning', 'pid': 8, 'tid': 139788553602880}
2023-07-31T14:17:59.644312Z [warning  ] Skipping async migrations setup. This is unsafe in production! [posthog.apps] pid=8 tid=139788553602880
2023-07-31T14:17:59.649550Z [info     ] AXES: BEGIN LOG                [axes.apps] pid=8 tid=139788553602880
2023-07-31T14:17:59.650183Z [info     ] AXES: Using django-axes version 5.9.0 [axes.apps] pid=8 tid=139788553602880
2023-07-31T14:17:59.650339Z [info     ] AXES: blocking by IP only.     [axes.apps] pid=8 tid=139788553602880
Operations to perform:
  Apply all migrations: admin, auth, axes, contenttypes, ee, posthog, sessions, social_django
Running migrations:
  No migrations to apply.
{'event': ['Skipping service version requirements. This is dangerous and PostHog might not work as expected!'], 'timestamp': '2023-07-31T14:18:03.581846Z', 'logger': 'posthog.settings.service_requirements', 'level': 'warning', 'pid': 11, 'tid': 140204546430784}
2023-07-31T14:18:04.406259Z [warning  ] Skipping async migrations setup. This is unsafe in production! [posthog.apps] pid=11 tid=140204546430784
2023-07-31T14:18:04.411193Z [info     ] AXES: BEGIN LOG                [axes.apps] pid=11 tid=140204546430784
2023-07-31T14:18:04.411741Z [info     ] AXES: Using django-axes version 5.9.0 [axes.apps] pid=11 tid=140204546430784
2023-07-31T14:18:04.411885Z [info     ] AXES: blocking by IP only.     [axes.apps] pid=11 tid=140204546430784
Traceback (most recent call last):
  File "/python-runtime/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/python-runtime/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/python-runtime/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/python-runtime/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/python-runtime/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/python-runtime/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/python-runtime/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/python-runtime/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f83d3bd19d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/python-runtime/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/python-runtime/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/python-runtime/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f83d3bd19d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/python-runtime/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/python-runtime/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/python-runtime/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/python-runtime/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/code/posthog/management/commands/migrate_clickhouse.py", line 42, in handle
    self.migrate(CLICKHOUSE_HTTP_URL, options)
  File "/code/posthog/management/commands/migrate_clickhouse.py", line 45, in migrate
    database = Database(
  File "/python-runtime/infi/clickhouse_orm/database.py", line 114, in __init__
    self.db_exists = self._is_existing_database()
  File "/python-runtime/infi/clickhouse_orm/database.py", line 436, in _is_existing_database
    r = self._send("SELECT count() FROM system.databases WHERE name = '%s'" % self.db_name)
  File "/python-runtime/infi/clickhouse_orm/database.py", line 387, in _send
    r = self.request_session.post(self.db_url, params=params, data=data, stream=stream, timeout=self.timeout)
  File "/python-runtime/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/python-runtime/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/python-runtime/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/python-runtime/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=8443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f83d3bd19d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Thank you

**Comment by oburd** [comment]
where i can change CLICKHOUSE_HTTP_URL in posthog ?

**Comment by siddiqss** [comment]
Have you gone through setting up PostHog locally?
Please recheck the steps. Maybe try setting up again. 
https://posthog.com/handbook/engineering/developing-locally

Also make sure you're using Linux or MacOS. Some tools are not supported on Windows.

**Comment by oburd** [comment]
> Have you gone through setting up PostHog locally? Please recheck the steps. Maybe try setting up again. https://posthog.com/handbook/engineering/developing-locally
> 
> Also make sure you're using Linux or MacOS. Some tools are not supported on Windows.

I'm doing in kubernetes, but i'm not understand, about clickhouse, what variable can i put for changing  CLICKHOUSE_HTTP_URL ?
Because we have our clickhouse in kubernetes and i want to use our clickhouse database

**Comment by oburd** [comment]
I only want to know how to change CLICKHOUSE_HTTP_URL
I have tried to add variable but it doesn't help me
