### ISSUE TITLE
Error upgrading hobby deploy: 111 Connection refused

### ISSUE THREAD

**Issue by thelazyoxymoron** [PostHog/posthog#17166]
## Bug description

When trying to upgrade a `1.43.1` installation to `latest`, plugins and worker containers are stuck in a crash loop with the following error:

```
{"level":"info","time":1692865173629,"pid":20,"hostname":"4f17f310892b","msg":"[MAIN] ℹ️ Connecting to all services:"}
{"level":"info","time":1692865173646,"pid":20,"hostname":"4f17f310892b","msg":"[MAIN] 🤔 Connecting to ClickHouse..."}
{"level":"error","time":1692865173663,"pid":20,"hostname":"4f17f310892b","error":"Error: connect ECONNREFUSED 192.168.208.7:8123\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","msg":"[MAIN] 💥 Launchpad failure!"}
{"level":"error","time":1692865173663,"pid":20,"hostname":"4f17f310892b","error":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"192.168.208.7","port":8123},"msg":"[MAIN] 💥 Exception while starting server, shutting down!"}
{"level":"info","time":1692865173663,"pid":20,"hostname":"4f17f310892b","msg":"[MAIN] 💤  Shutting down gracefully..."}
{"level":"info","time":1692865173664,"pid":20,"hostname":"4f17f310892b","msg":"[MAIN] 👋 Over and out!"}
```

```
Traceback (most recent call last):
  File "/python-runtime/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/python-runtime/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/python-runtime/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='clickhouse', port=8123): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa39707f970>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

## How to reproduce

1. Run a hobby deploy for release `1.43.1`
2. Switch to latest master and run the upgrade script

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [ ] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [x] PostHog Hobby self-hosted with `docker compose`, commit: `a21eb971f3a6d958504aa3df448a33f2ca6db58d`
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by thelazyoxymoron** [comment]
This is too old now to matter, closing
