### ISSUE TITLE
Unable to send and receive emails

### ISSUE THREAD

**Issue by maxfsc** [PostHog/posthog#18354]
## Bug description

We've tried to configure a remote email server with PostHog (thanks to the doc: https://posthog.com/docs/self-host/configure/email). 

But despite a correct SMTP configuration, the platform is not able to send emails.

We're using a docker-compose installation based on the Posthog doc. 
When using the python email sending test command: "python manage.py sendtestemail _myname@domain_", we have the following traceback:

```
Traceback (most recent call last):
  File "/code/manage.py", line 21, in <module>
    main()
  File "/code/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/python-runtime/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/python-runtime/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/python-runtime/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/python-runtime/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/python-runtime/django/core/management/commands/sendtestemail.py", line 29, in handle
    send_mail(
  File "/python-runtime/django/core/mail/__init__.py", line 61, in send_mail
    return mail.send()
  File "/python-runtime/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/python-runtime/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/python-runtime/django/core/mail/backends/smtp.py", line 62, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_
```

Have you ever experienced this? Do you know how to solve it?

## How to reproduce

1. Self-host PostHog user a docker-compose
2. Follow this doc to configure email : https://posthog.com/docs/self-host/configure/email
3. Try to send yourself an email

## Environment

PostHog Hobby self-hosted with `docker compose`

## Additional context

None

**Comment by paul-uz** [comment]
How do you configure the email? I'm using self hosted but can't find anywhere to configure SMTP.
