### ISSUE TITLE
Hobby deployment not working for MacOS

### ISSUE THREAD

**Issue by Makki93** [PostHog/posthog#18840]
## Bug description

Hey guys,
first, thanks for the offer of the self-hosted hobby project version of posthog. I wanted to test it for my team, but i ran into several issues.

The script that you offer in your self-hosted guys only works on linux, i tried modifying it so it would use homebrew on the respective parts. Then, i had to add a TRUSTED_PROXIES entry for the environment variables of the docker-compose.hobby.yml. But still, the web server won't start up. 
It seems that the web server can't connect to the clickhouse server, and to the kafka server. No idea why. 

Any idea, what's the issue? Also, is there a script planned for mac?

Here are the logs:
`2023-11-23T09:28:19.562187Z [warning  ] Failed to connect to clickhouse:9440 [clickhouse_driver.connection] pid=5 tid=281472917269776
Traceback (most recent call last):
  File "/python-runtime/clickhouse_driver/connection.py", line 318, in connect
    return self._init_connection(host, port)
  File "/python-runtime/clickhouse_driver/connection.py", line 282, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/python-runtime/clickhouse_driver/connection.py", line 254, in _create_socket
    raise err
  File "/python-runtime/clickhouse_driver/connection.py", line 245, in _create_socket
    sock.connect(sa)
  File "/usr/local/lib/python3.8/ssl.py", line 1342, in connect
    self._real_connect(addr, False)
  File "/usr/local/lib/python3.8/ssl.py", line 1329, in _real_connect
    super().connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/python-runtime/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/python-runtime/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/python-runtime/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/python-runtime/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/code/posthog/apps.py", line 52, in ready
    in_range, version = service_version_requirement.is_service_in_accepted_version()
  File "/code/posthog/version_requirement.py", line 28, in is_service_in_accepted_version
    service_version = self.get_service_version()
  File "/code/posthog/version_requirement.py", line 36, in get_service_version
    return get_clickhouse_version()
  File "/code/posthog/version_requirement.py", line 58, in get_clickhouse_version
    rows = client.execute("SELECT version()")
  File "/python-runtime/clickhouse_driver/client.py", line 252, in execute
    self.connection.force_connect()
  File "/python-runtime/clickhouse_driver/connection.py", line 212, in force_connect
    self.connect()
  File "/python-runtime/clickhouse_driver/connection.py", line 339, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. Connection refused (clickhouse:9440)
▶️ Starting plugin server...
{"level":"info","time":1700731703420,"pid":9,"hostname":"ed3c8f25e3e1","msg":"[MAIN] ⚡ @posthog/plugin-server v1.10.5"}
{"level":"info","time":1700731703439,"pid":9,"hostname":"ed3c8f25e3e1","msg":"[MAIN] ℹ️ 1 workers, 10 tasks per worker"}
{"level":"info","time":1700731703441,"pid":9,"hostname":"ed3c8f25e3e1","msg":"[MAIN] ℹ️ Connecting to all services:"}
{"level":"info","time":1700731703465,"pid":9,"hostname":"ed3c8f25e3e1","msg":"[MAIN] 🤔 Connecting to ClickHouse..."}
{"level":"info","time":1700731703551,"pid":9,"hostname":"ed3c8f25e3e1","msg":"[MAIN] 👍 ClickHouse ready"}
{"level":"info","time":1700731703552,"pid":9,"hostname":"ed3c8f25e3e1","msg":"[MAIN] 🤔 Connecting to Kafka..."}
{"level":"ERROR","timestamp":"2023-11-23T09:28:23.594Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 10.89.4.26:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-018bfb82-5091-0000-45d6-ed559693f7f8","stack":"Error: connect ECONNREFUSED 10.89.4.26:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)"}
{"level":"ERROR","timestamp":"2023-11-23T09:28:23.596Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 10.89.4.26:9092","retryCount":0,"retryTime":271}
{"level":"ERROR","timestamp":"2023-11-23T09:28:23.873Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 10.89.4.26:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-018bfb82-5091-0000-45d6-ed559693f7f8","stack":"Error: connect ECONNREFUSED 10.89.4.26:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)"}
{"level":"ERROR","timestamp":"2023-11-23T09:28:23.874Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 10.89.4.26:9092","retryCount":1,"retryTime":586}
{"level":"ERROR","timestamp":"2023-11-23T09:28:24.467Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 10.89.4.26:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-018bfb82-5091-0000-45d6-ed559693f7f8","stack":"Error: connect ECONNREFUSED 10.89.4.26:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)"}
{"level":"ERROR","timestamp":"2023-11-23T09:28:24.467Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 10.89.4.26:9092","retryCount":2,"retryTime":1168}
{"level":"ERROR","timestamp":"2023-11-23T09:28:25.654Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 10.89.4.26:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-018bfb82-5091-0000-45d6-ed559693f7f8","stack":"Error: connect ECONNREFUSED 10.89.4.26:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)"}
{"level":"ERROR","timestamp":"2023-11-23T09:28:25.656Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 10.89.4.26:9092","retryCount":3,"retryTime":2470}
{"level":"ERROR","timestamp":"2023-11-23T09:28:28.131Z","logger":"kafkajs","message":"[Connection] Connection error: connect ECONNREFUSED 10.89.4.26:9092","broker":"kafka:9092","clientId":"plugin-server-v1.10.5-018bfb82-5091-0000-45d6-ed559693f7f8","stack":"Error: connect ECONNREFUSED 10.89.4.26:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)"}
{"level":"ERROR","timestamp":"2023-11-23T09:28:28.132Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 10.89.4.26:9092","retryCount":4,"retryTime":4690}`

**Comment by Inder782** [comment]
Did you first try running the  /bin/bash without modifying it, I don' think there is a need to modify anything on mac,

**Comment by Makki93** [comment]
Hi @Inder782, thanks for answering.

Yes i tried that,
but looking at it's code, it was easy to see that there are some linux-specific commands in there.
E.g. updating apt, which does not exist on mac.

`# update apt cache
echo "Grabbing latest apt caches"
sudo apt update

# clone posthog
echo "Installing PostHog 🦔 from Github"
sudo apt install -y git
# try to clone - if folder is already there pull latest for that branch
git clone https://github.com/PostHog/posthog.git &> /dev/null || true
cd posthog`

But that was not the issue, it was really the problem with non connecting database and kafka.
You can test the script that i slightly modified (rename from .txt to .sh to test it):
[deploy-postHog-selfhosted.txt](https://github.com/PostHog/posthog/files/13513249/deploy-postHog-selfhosted.txt)
