### ISSUE TITLE
changing timeframe of dashboard breaking while using google translate

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#19663]
## Bug description

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at QF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:26102)
    at Lu (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:25789)
    at QF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:26863)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27395)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27658)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27658)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27658)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:30596)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27658)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27793)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27658)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27855)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27658)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27658)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
    at jF (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27658)
    at Wi (https://app-static-prod.posthog.com/static/chunk-R7DGFOT7.js:13:27545)
```

## How to reproduce

1. Go to dashboard
2. Translate page to German with Google Chrome
3. Update the date range (e.g. last 30 to last 7 days)

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/8796

**Comment by mariusandra** [comment]
Google Translate doesn't like text that's not perfectly enclosed in a container.

- `<div>Translates well</div>`
- `<div><div>Translates well</div> Loose element, might have issues </div>`

**Comment by darkopia** [comment]
https://posthoghelp.zendesk.com/agent/tickets/19831 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/22122)
