### ISSUE TITLE
database migration failes when upgrading from 1.14.0 to 1.15.0

### ISSUE THREAD

**Issue by toxsick** [PostHog/posthog#2106]
## Bug description

When upgrading my self-hosted Kubernetes Posthog deployment from 1.14.0 to 1.15.0 the database migration failed with:

```
2020-10-29T13:20:54.553445511+01:00 Operations to perform:
2020-10-29T13:20:54.553510483+01:00   Apply all migrations: admin, auth, contenttypes, posthog, sessions, social_django
2020-10-29T13:20:54.587958604+01:00 Running migrations:
2020-10-29T13:20:56.003242534+01:00 Traceback (most recent call last):
2020-10-29T13:20:56.003281412+01:00   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
2020-10-29T13:20:56.003291733+01:00     return self.cursor.execute(sql, params)
2020-10-29T13:20:56.003300450+01:00 psycopg2.errors.ObjectInUse: FEHLER:  CREATE INDEX mit Relation »posthog_annotation« nicht möglich, weil es anstehende Trigger-Ereignisse dafür gibt
2020-10-29T13:20:56.003311335+01:00 
2020-10-29T13:20:56.003317984+01:00 
2020-10-29T13:20:56.003324874+01:00 The above exception was the direct cause of the following exception:
2020-10-29T13:20:56.003332565+01:00 
2020-10-29T13:20:56.003339208+01:00 Traceback (most recent call last):
2020-10-29T13:20:56.003345816+01:00   File "manage.py", line 21, in <module>
2020-10-29T13:20:56.003352659+01:00     main()
2020-10-29T13:20:56.003359499+01:00   File "manage.py", line 17, in main
2020-10-29T13:20:56.003366000+01:00     execute_from_command_line(sys.argv)
2020-10-29T13:20:56.003374133+01:00   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
2020-10-29T13:20:56.003382650+01:00     utility.execute()
2020-10-29T13:20:56.003389699+01:00   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
2020-10-29T13:20:56.003397007+01:00     self.fetch_command(subcommand).run_from_argv(self.argv)
2020-10-29T13:20:56.003403779+01:00   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
2020-10-29T13:20:56.003410385+01:00     self.execute(*args, **cmd_options)
2020-10-29T13:20:56.003416947+01:00   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
2020-10-29T13:20:56.003423576+01:00     output = self.handle(*args, **options)
2020-10-29T13:20:56.003430028+01:00   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
2020-10-29T13:20:56.003436560+01:00     res = handle_func(*args, **kwargs)
2020-10-29T13:20:56.003443272+01:00   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 231, in handle
2020-10-29T13:20:56.003449841+01:00     post_migrate_state = executor.migrate(
2020-10-29T13:20:56.003456239+01:00   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
2020-10-29T13:20:56.003462724+01:00     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
2020-10-29T13:20:56.003469303+01:00   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
2020-10-29T13:20:56.003476066+01:00     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
2020-10-29T13:20:56.003482781+01:00   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 247, in apply_migration
2020-10-29T13:20:56.003489444+01:00     migration_recorded = True
2020-10-29T13:20:56.003495926+01:00   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 115, in __exit__
2020-10-29T13:20:56.003502448+01:00     self.execute(sql)
2020-10-29T13:20:56.003509183+01:00   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 142, in execute
2020-10-29T13:20:56.003515869+01:00     cursor.execute(sql, params)
2020-10-29T13:20:56.003540236+01:00   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
2020-10-29T13:20:56.003547894+01:00     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2020-10-29T13:20:56.003554958+01:00   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
2020-10-29T13:20:56.003561847+01:00     return executor(sql, params, many, context)
2020-10-29T13:20:56.003569505+01:00   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
2020-10-29T13:20:56.003575977+01:00     return self.cursor.execute(sql, params)
2020-10-29T13:20:56.003582439+01:00   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
2020-10-29T13:20:56.003589061+01:00     raise dj_exc_value.with_traceback(traceback) from exc_value
2020-10-29T13:20:56.003596398+01:00   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
2020-10-29T13:20:56.003618156+01:00     return self.cursor.execute(sql, params)
2020-10-29T13:20:56.003627308+01:00 django.db.utils.OperationalError: FEHLER:  CREATE INDEX mit Relation »posthog_annotation« nicht möglich, weil es anstehende Trigger-Ereignisse dafür gibt
2020-10-29T13:20:56.003633833+01:00 
2020-10-29T13:20:56.336315537+01:00   Applying posthog.0085_org_models...
```

I guess it failes to create an index in `posthog_annotation` due to existing trigger events (not sure what that means).

## Environment

- PostHog self-managed on kubernetes using helm chart

regards

**Comment by toxsick** [comment]
Ok found it. I think I created an Annotation when my workers where not running before. I removed this entry from the table `posthog_annotation` manually (only had this one) and the migration worked. I think it is an edge case, but not sure what to do it I already had other annotations.

Whatever, closing this for now..
