### ISSUE TITLE
`await client.shutdown()` causing errors

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#21110]
## Bug description

When calling this:
```
import { PostHog } from 'posthog-node'

const client = new PostHog(
    'phc_uLJDHZ1KJcrjI8ivesqq247KXt8W2KJQ15GUF27jjR0',
    { host: "https://us.posthog.com" }
)

client.capture('test-event')

await client.shutdown() 
```

We'll get this error:
```
Error while shutting down PostHog PostHogFetchHttpError: HTTP error while fetching PostHog: 400
    at retriable (/Users/marcon/Downloads/work/node-bug-test/node_modules/posthog-node/lib/index.cjs.js:1350:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retriable (/Users/marcon/Downloads/work/node-bug-test/node_modules/posthog-node/lib/index.cjs.js:43:25)
    at async PostHog.fetchWithRetry (/Users/marcon/Downloads/work/node-bug-test/node_modules/posthog-node/lib/index.cjs.js:1333:16)
    at async PostHog._flush (/Users/marcon/Downloads/work/node-bug-test/node_modules/posthog-node/lib/index.cjs.js:1311:13) {
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 400,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Bad Request',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}
```

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/11962

**Comment by MarconLP** [comment]
We have to capture events like this instead:
```
client.capture({
    distinctId: 'distinct_id_of_your_user',
    event: 'event_name',
    sendFeatureFlags: true,
})
```

**Comment by MarconLP** [comment]
> @MarconLP do you always need to set `sendFeatureFlags` or does it work without it too? If the former, a bug for us 😬

Not setting `sendFeatureFlags` work's as well. I just copied what's recommended on the nodejs setup guide.
```
client.capture({
    distinctId: 'distinct_id_of_your_user',
    event: 'event_name'
})
```

**Comment by neilkakkar** [comment]
Ahh I didn't realise what was different 😂  -> it's that `client.capture('test-event')` has no object and direct event name. Cool cool
