### ISSUE TITLE
Next.js error pre-rendering pages

### ISSUE THREAD

**Issue by danilofuchs** [PostHog/posthog#21545]
## Bug description

Using Next.js Pages Router, PostHog/React crashes build for static pages

`posthog-js > 1.111.0`

(1.111.0 builds correctly)

## How to reproduce

1. Create Next.js 14.1.4 project with pages router, Typescript, Tailwind
2. Add PostHog provider to _app.tsx:
```typescript
// PostHogProvider.tsx
import { useUser } from "@clerk/nextjs";
import { PostHogProvider as Provider, usePostHog } from "posthog-js/react";
import { useEffect } from "react";
import { env } from "~/env.js";

interface Props {
  children: React.ReactNode;
}

export const PostHogProvider = ({ children }: Props) => {
  return (
    <Provider apiKey={env.NEXT_PUBLIC_POSTHOG_KEY}>
      <PostHogUserSync />
      {children}
    </Provider>
  );
};

const PostHogUserSync = () => {
  const postHog = usePostHog();
  const { user, isLoaded, isSignedIn } = useUser();

  useEffect(() => {
    if (user && isLoaded && isSignedIn) {
      postHog.identify(user.id, {
        email: user.primaryEmailAddress?.emailAddress,
        companyId: user.publicMetadata.companyId,
        role: user.publicMetadata.role,
      });
    }

    if (isLoaded && !isSignedIn) {
      postHog.reset();
    }
  }, [user, isLoaded, isSignedIn, postHog]);

  return null;
};
```
```typescript
// _app.tsx
return (
  <PostHogProvider>
    <Component {...pageProps} />
  </PostHogProvider>
)
```
4. Add a static pages
5. `next build`

```
Error occurred prerendering page "/page". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: L is not a constructor
    at ir (/home/danilo/salvy/salvy-dashboard/node_modules/posthog-js/dist/module.js:1:77114)
    at /home/danilo/salvy/salvy-dashboard/node_modules/posthog-js/dist/module.js:1:108975
    at e.value (/home/danilo/salvy/salvy-dashboard/node_modules/posthog-js/dist/module.js:1:108987)
    at e.value (/home/danilo/salvy/salvy-dashboard/node_modules/posthog-js/dist/module.js:1:62848)
    at e.value (/home/danilo/salvy/salvy-dashboard/node_modules/posthog-js/dist/module.js:1:107558)
    at e.value (/home/danilo/salvy/salvy-dashboard/node_modules/posthog-js/dist/module.js:1:106745)
    at e.value (/home/danilo/salvy/salvy-dashboard/node_modules/posthog-js/dist/module.js:1:103481)
    at /home/danilo/salvy/salvy-dashboard/node_modules/posthog-js/react/dist/umd/index.js:30:47
    at Object.Kc [as useMemo] (/home/danilo/salvy/salvy-dashboard/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
    at exports.useMemo (/home/danilo/salvy/salvy-dashboard/node_modules/react/cjs/react.production.min.js:25:208)
[PostHog.js] was already loaded elsewhere. This may cause issues.
[PostHog.js] was already loaded elsewhere. This may cause issues.
[PostHog.js] was already loaded elsewhere. This may cause issues.
[PostHog.js] was already loaded elsewhere. This may cause issues.
[PostHog.js] was already loaded elsewhere. This may cause issues.
[PostHog.js] was already loaded elsewhere. This may cause issues.
[PostHog.js] was already loaded elsewhere. This may cause issues.
[PostHog.js] was already loaded elsewhere. This may cause issues.
[PostHog.js] was already loaded elsewhere. This may cause issues.
[PostHog.js] was already loaded elsewhere. This may cause issues.
[PostHog.js] was already loaded elsewhere. This may cause issues.
```

## Additional context

`L` is minified, appears to be an HTTP fetcher
![image](https://github.com/PostHog/posthog/assets/17657014/c3db5536-dc04-4b78-b7be-31a2d65f2b74)

**Comment by danilofuchs** [comment]
Wrong repo, reoppening in posthog-js https://github.com/PostHog/posthog-js/issues/1139
