### ISSUE TITLE
Posthog crashes seconds after I open a session recording in dashboard

### ISSUE THREAD

**Issue by Abhid14** [PostHog/posthog#21874]
## Posthog crashes seconds after I open a recording.

When I open a session recording on Posthog it crashes.

## How to reproduce

1. Go to Posthog Dashboard open a session or any long session recording
2. You will see Posthog Crashing

Screenshot

<img width="1624" alt="Screenshot 2024-04-26 at 09 56 54" src="https://github.com/PostHog/posthog/assets/34400585/35f1d3f2-771b-47f8-9b87-f1b917c228cb">

Crash Logs:

An error has occurred
TypeError: a.pause is not a function
    at https://app-static-prod.posthog.com/static/chunk-V7DPKPDG.js:707:39879
    at Map.forEach (<anonymous>)
    at Fw.syncAllMediaElements (https://app-static-prod.posthog.com/static/chunk-V7DPKPDG.js:707:39824)
    at Fw.pause (https://app-static-prod.posthog.com/static/chunk-V7DPKPDG.js:707:39938)
    at https://app-static-prod.posthog.com/static/chunk-V7DPKPDG.js:707:27732
    at Array.map (<anonymous>)
    at Object.emit (https://app-static-prod.posthog.com/static/chunk-V7DPKPDG.js:707:27716)
    at QG.pause (https://app-static-prod.posthog.com/static/chunk-V7DPKPDG.js:707:51611)
    at setPause (https://app-static-prod.posthog.com/static/chunk-V7DPKPDG.js:708:49763)
    at https://app-static-prod.posthog.com/static/chunk-NB5N7CJB.js:2:10493
    at Object.dispatch (https://app-static-prod.posthog.com/static/chunk-NB5N7CJB.js:2:22661)
    at t.actions.<computed> (https://app-static-prod.posthog.com/static/chunk-NB5N7CJB.js:2:12293)
    at JRt.Nf.maxWait (https://app-static-prod.posthog.com/static/chunk-V7DPKPDG.js:709:8470)
    at k (https://app-static-prod.posthog.com/static/chunk-V7DPKPDG.js:213:915)
    at S (https://app-static-prod.posthog.com/static/chunk-V7DPKPDG.js:213:1563)
    at https://app-static-prod.posthog.com/static/chunk-V7DPKPDG.js:709:8530
    at _u (https://app-static-prod.posthog.com/static/chunk-NB5N7CJB.js:13:24250)
    at ia (https://app-static-prod.posthog.com/static/chunk-NB5N7CJB.js:13:42327)
    at https://app-static-prod.posthog.com/static/chunk-NB5N7CJB.js:13:40664
    at Nd (https://app-static-prod.posthog.com/static/chunk-NB5N7CJB.js:6:26129)
    at MessagePort.Vd (https://app-static-prod.posthog.com/static/chunk-NB5N7CJB.js:6:26523)

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018f188b-6ba8-7b2f-9bdd-7cc839a5c04c?t=1550 (at https://us.posthog.com/project/63817#sessionRecordingId=018f189e-2825-70db-b545-c9874df9ae73&panel=support%3Abug%3A%3A)
Admin: http://go/adminOrgUS/018ee1ab-f990-0000-c733-b899762709c8 (Project: 63817)
Sentry: http://go/sentryUS/63817
```

**Comment by marandaneto** [comment]
Hi @Abhid14 sorry about that, we're currently investigating this issue, thanks.

**Comment by daibhin** [comment]
Still being reported as of https://posthoghelp.zendesk.com/agent/tickets/13038 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/15594)

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog/pull/22060 fixes it
