### ISSUE TITLE
Error using `disable_external_dependency_loading=true` in NextJS

### ISSUE THREAD

**Issue by jwayne** [PostHog/posthog#24226]
## Bug description

I get the following error when I call `posthog.init` in a NextJS app with `disable_external_dependency_loading: true`. This error appears in my terminal when I run `npm run dev`.

```
 GET / 500 in 36ms
 ⨯ TypeError: Cannot set properties of undefined (setting 'posthogErrorWrappingFunctions')
    at __webpack_require__ (/Users/joshchen/proj/learning/test-posthog/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/analytics.ts:9:95)
    at (ssr)/./src/app/analytics.ts (/Users/joshchen/proj/learning/test-posthog/.next/server/app/page.js:173:1)
    at __webpack_require__ (/Users/joshchen/proj/learning/test-posthog/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/AnalyticsProvider.tsx:9:72)
    at (ssr)/./src/app/AnalyticsProvider.tsx (/Users/joshchen/proj/learning/test-posthog/.next/server/app/page.js:162:1)
    at Object.__webpack_require__ [as require] (/Users/joshchen/proj/learning/test-posthog/.next/server/webpack-runtime.js:33:42)
digest: "1030166450"
```

## How to reproduce

I have a minimal repro here, where I installed Posthog into a NextJS starter app and called `posthog.init` with `disable_external_dependency_loading: true`: https://github.com/jwayne/test-posthog

In this repro, I've imported all the recommended extensions as per [these docs](https://posthog.com/docs/libraries/js#advanced-option---bundle-all-required-extensions):

```
import "posthog-js/dist/recorder"
import "posthog-js/dist/surveys"
import "posthog-js/dist/exception-autocapture"
import "posthog-js/dist/tracing-headers"
import "posthog-js/dist/web-vitals"
```

## Additional context

I want to use `disable_external_dependency_loading: true` because I want to run posthog in a Chrome extension, and Chrome extensions disallow external script loading.

### Debug info

```
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/01912906-0908-7899-bf74-dc5282c904ce?t=0
Admin: http://go/adminOrgUS/01911fa4-88e3-0000-9070-c8765035ffa5 (project ID 83184)
Sentry: http://go/sentryUS/83184
```

**Comment by jwayne** [comment]
Closing in favor of mentioned issue, since `posthog-js` seems like a better repo to post this issue in
