### ISSUE TITLE
Developing locally using posthog-foss fails

### ISSUE THREAD

**Issue by harryqt** [PostHog/posthog#25023]
When [developing-locally](https://posthog.com/handbook/engineering/developing-locally) using [posthog-foss](https://github.com/PostHog/posthog-foss), can't get past `DEBUG=1 ./bin/migrate`

```
(env) harry@ubuntu24:~/posthog-foss$ ./bin/migrate
Performing cyclotron migrations for postgres://posthog:posthog@localhost:5432/cyclotron (DATABASE_NAME=cyclotron)
    Updating crates.io index
     Ignored package `sqlx-cli v0.8.2` is already installed, use --force to override
Applied 20240804122549/migrate initial job queue schema (38.615316ms)
Applied 20240823191751/migrate bytes over text (22.500356ms)
2024-09-17 17:08:42 [warning  ] ['️Environment variable DEBUG is set - PostHog is running in DEVELOPMENT MODE!', 'Be sure to unset DEBUG if this is supposed to be a PRODUCTION ENVIRONMENT!']
Traceback (most recent call last):
  File "/home/harry/posthog-foss/manage.py", line 22, in <module>
    main()
  File "/home/harry/posthog-foss/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/harry/posthog-foss/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/harry/posthog-foss/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/harry/posthog-foss/env/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/harry/posthog-foss/env/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/harry/posthog-foss/env/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harry/posthog-foss/posthog/models/__init__.py", line 54, in <module>
    from .organization_invite import OrganizationInvite
  File "/home/harry/posthog-foss/posthog/models/organization_invite.py", line 9, in <module>
    from ee.models.explicit_team_membership import ExplicitTeamMembership
ModuleNotFoundError: No module named 'ee'
(env) harry@ubuntu24:~/posthog-foss$ 
```

`ee` directory not present in foss version, thus failing: [organization_invite.py#L9](https://github.com/PostHog/posthog/blob/cf61ed73fad1d71422bb897107ef16ad6c556c11/posthog/models/organization_invite.py#L9)

**Comment by benjackwhite** [comment]
Will update the docs. You need to run `cargo install sqlx-cli`

**Comment by harryqt** [comment]
> You need to run `cargo install sqlx-cli`

Its already installed. The actual issue coming from:

```
  File "/home/harry/posthog-foss/posthog/models/organization_invite.py", line 9, in <module>
    from ee.models.explicit_team_membership import ExplicitTeamMembership
ModuleNotFoundError: No module named 'ee'
(env) harry@ubuntu24:~/posthog-foss$ 
```

**Comment by harryqt** [comment]
> You need to run `cargo install sqlx-cli`

I installed it again also using --force, but still same error. :/

**Comment by myturn0** [comment]
@harryqt Have you solved this problem? How did you solve it?

**Comment by harryqt** [comment]
Nope. :(

**Comment by myturn0** [comment]
:(. Do we need to rewrite this code or buy the commercial version?

**Comment by harryqt** [comment]
i guess the latter.. lol
