### ISSUE TITLE
Self Hosted Posthog: Validation checks failing

### ISSUE THREAD

**Issue by rohitdhas** [PostHog/posthog#25442]
## Bug description

I’ve installed PostHog on a Linode server but I'm unable to launch it in live mode due to a validation error. The error appears to be related to the `Plugin Server · Node` check, which is failing.

Server Specifications:
- RAM: 16 GB
- CPU Cores: 8
- OS: Ubuntu 24.04 LTS

Question:
- How can I resolve this issue and successfully launch PostHog in live mode?

![image](https://github.com/user-attachments/assets/c496f484-d628-417c-b69d-46f89fa8be65)

**Comment by JoyShaheb** [comment]
i have been facing the same issue as well on self hosted version. following this to get updates

**Comment by pauldambra** [comment]
can you get the logs from the plugin server container?
hard to know what's happening without any logs 😅

**Comment by pauldambra** [comment]
Ah... I updated my self-hosted install and think i see what the what

https://github.com/PostHog/posthog/pull/25454

**Comment by pauldambra** [comment]
Hey I believe this is fixed by #25518 (certainly fixed my self hosted instance)

If you run the upgrade script we should now generate the key you need and things will start

**Comment by rohitdhas** [comment]
@pauldambra got this error while upgrading:
```
ENCRYPTION_SALT_KEYS is not in the correct fernet format and will not work
🛑 Stop this script and do not proceed
remove ENCRYPTION_SALT_KEYS from .env and try again
```

**Comment by pauldambra** [comment]
hey... 

you might need this fix https://github.com/PostHog/posthog/pull/25526 - I do

otherwise it might be a different problem

can you share the output from `docker logs root-plugins-1`?

**Comment by rohitdhas** [comment]
@pauldambra 

```
▶️ Starting plugin server...
{"level":"info","time":1728589278171,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] ⚡ @posthog/plugin-server v1.10.5"}
{"level":"info","time":1728589278182,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] ℹ️ 1 workers, 10 tasks per worker"}
(node:73) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
{"level":"info","time":1728589278183,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] ℹ️ Connecting to all services:"}
{"level":"info","time":1728589278209,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] 🤔 Connecting to ClickHouse..."}
{"level":"info","time":1728589278209,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] 👍 ClickHouse ready"}
{"level":"info","time":1728589278209,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] 🤔 Connecting to Kafka..."}
{"level":"info","time":1728589278220,"pid":73,"hostname":"57b7baed6dcd","error":null,"brokers":[{"id":1001,"host":"kafka","port":9092}],"msg":"[MAIN] 📝 librdkafka producer connected"}
{"level":"info","time":1728589278220,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] 👍 Kafka ready"}
{"level":"info","time":1728589278220,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] 🤔 Connecting to common Postgresql..."}
{"level":"info","time":1728589278221,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] 👍 Common Postgresql ready"}
{"level":"info","time":1728589278221,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] 👍 Postgres Router ready"}
{"level":"info","time":1728589278221,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] 🤔 Connecting to Redis..."}
{"level":"info","time":1728589278228,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] 👍 Redis ready"}
{"level":"info","time":1728589278228,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] 🤔 Connecting to object storage..."}
{"level":"info","time":1728589278235,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] 👍 Object storage ready"}
{"level":"error","time":1728589278245,"pid":73,"hostname":"57b7baed6dcd","error":"Error: Encryption keys are not set\n    at new EncryptedFields (/code/plugin-server/dist/cdp/encryption-utils.js:10:19)\n    at createHub (/code/plugin-server/dist/utils/db/hub.js:184:26)\n    at async setupHub (/code/plugin-server/dist/main/pluginsServer.js:157:34)\n    at async startPluginsServer (/code/plugin-server/dist/main/pluginsServer.js:166:25)","msg":"[MAIN] 💥 Launchpad failure!"}
{"level":"error","time":1728589278245,"pid":73,"hostname":"57b7baed6dcd","error":{},"msg":"[MAIN] 💥 Exception while starting server, shutting down!"}
{"level":"info","time":1728589278245,"pid":73,"hostname":"57b7baed6dcd","msg":"[MAIN] 💤  Shutting down gracefully..."}
2024-10-10T19:41:33.991391Z [warning  ] Skipping async migrations setup. This is unsafe in production! [posthog.apps] pid=10 tid=130422590314304
2024-10-10T19:41:33.997465Z [info     ] AXES: BEGIN LOG                [axes.apps] pid=10 tid=130422590314304
2024-10-10T19:41:33.997951Z [info     ] AXES: Using django-axes version 5.9.0 [axes.apps] pid=10 tid=130422590314304
2024-10-10T19:41:33.998135Z [info     ] AXES: blocking by IP only.     [axes.apps] pid=10 tid=130422590314304
```

**Comment by pauldambra** [comment]
Yep, I think https://github.com/PostHog/posthog/pull/25526 is the one then...

I'll ping here when the image is available

**Comment by pauldambra** [comment]
That fixed for me... can you try again? Thanks!

**Comment by StrandedKitty** [comment]
This issue is still present with a clean install from `latest`

**Comment by StrandedKitty** [comment]
Fixed the issue by replacing 
```
ENCRYPTION_KEY=$(openssl rand -hex 16)
export ENCRYPTION_SALT_KEYS
```
with
```
ENCRYPTION_SALT_KEYS=$(openssl rand -hex 16)
export ENCRYPTION_SALT_KEYS
```
in `bin/deploy-hobby`.

**Comment by rohitdhas** [comment]
@StrandedKitty should I restart the containers after this change??

**Comment by StrandedKitty** [comment]
> @StrandedKitty should I restart the containers after this change??

Not sure how to make it work if you already have your containers running. I imagine you have to edit .env somewhere inside some container.

**Comment by pauldambra** [comment]
Hey All,

You should only need to run the upgrade script if you're getting any errors related to `ENCRYPTION_SALT_KEYS`

https://posthog.com/docs/self-host#upgrading

**Comment by rohitdhas** [comment]
This is fixed, closing the issue!
