### ISSUE TITLE
posthog hobby install issue

### ISSUE THREAD

**Issue by stroeovidiu** [PostHog/posthog#25521]
## Bug description
I am trying to setup posthog using the hobby script and evertyhing seems to work except the plugin server which failes with:
"error":"Error: Key must be 32-byte long base64url encoded string.\n    at Fernet.checkKey (/code/plugin-server/node_modules/.pnpm/fernet-nodejs@1.0.6/node_modules/fernet-nodejs/dist/Fernet.js:28:19)\n    at new Fernet (/code/plugin-server/node_modules/.pnpm/fernet-nodejs@1.0.6/node_modules/fernet-nodejs/dist/Fernet.js:8:16)\n    at /code/plugin-server/dist/cdp/encryption-utils.js:12:46\n    at Array.map (<anonymous>)\n    at new EncryptedFields (/code/plugin-server/dist/cdp/encryption-utils.js:12:33)\n    at createHub (/code/plugin-server/dist/utils/db/hub.js:184:26)\n    at async setupHub (/code/plugin-server/dist/main/pluginsServer.js:157:34)\n    at async startPluginsServer (/code/plugin-server/dist/main/pluginsServer.js:166:25)","msg":"[MAIN] 💥 Launchpad failure!"}

## How to reproduce
Run the hobby install sctip

**Comment by pauldambra** [comment]
Hey I believe this is fixed by https://github.com/PostHog/posthog/pull/25518 (certainly fixed my self hosted instance)

If you run the upgrade script we should now generate the key you need and things will start
