### ISSUE TITLE
Internal server error with  /api/action/trends/

### ISSUE THREAD

**Issue by kasbah** [PostHog/posthog#338]
**Describe the bug**
I am getting an internal server error:

```
Internal Server Error: /api/action/trends/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/posthog/api/action.py", line 193, in trends
    actions = self.get_queryset()
  File "/code/posthog/api/action.py", line 75, in get_queryset
    queryset = queryset.filter(pk__in=[action['id'] for action in self._parse_actions(self.request.GET['actions'])])
  File "/code/posthog/api/action.py", line 75, in <listcomp>
    queryset = queryset.filter(pk__in=[action['id'] for action in self._parse_actions(self.request.GET['actions'])])
TypeError: 'int' object is not subscriptable
```

**To Reproduce**
I went through the following installation process:

- Installing via docker
- Stopping and removing the docker image (I wanted to get rid of the initial data, but actually forgot about removing volumes)
- Installing again via docker (and it did successfully reload with the old data, once at least if I recall correctly, now I am getting this error)

I can give you access to this test instance if that helps. It's currently on https://posthog.kitspace.org

**Expected behavior**
No error :wink:

**Comment by timgl** [comment]
I think you've got an old version of the frontend combined with a newer version of the backend. I think that's consistent with the fact you stopped and removed an older version of the docker image.

Could you try a hard refresh of the frontend (disable cache)?

If that doesn't work, could you send me a screenshot of the failing request in your network tab?

Thanks!

**Comment by kasbah** [comment]
I did a hard refresh but it didn't help. It's all in one docker container right, so it shouldn't be inconsistent there?

![image](https://user-images.githubusercontent.com/206854/76641234-2c642500-6549-11ea-8820-24b7ce300175.png)

Here is the second failing request copied as `fetch`. 

```js
await fetch("https://posthog.kitspace.org/api/action/trends/?actions=%5B1%5D", {
    "credentials": "include",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.120 Safari/537.36",
        "Accept": "*/*",
        "Accept-Language": "en-GB,en;q=0.5",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache"
    },
    "referrer": "https://posthog.kitspace.org/",
    "method": "GET",
    "mode": "cors"
});
```

**Comment by timgl** [comment]
Are you using `posthog/posthog:latest` as a docker image? We changed the frontend so the request should be different. Maybe worth pulling it again if you haven't yet?

**Comment by timgl** [comment]
@kasbah There hasn't been any action on this ticket in a while. Let me know if this still isn't solved when you upgrade to a newer version?
