### ISSUE TITLE
Plugin server is NOT working on Heroku

### ISSUE THREAD

**Issue by avorio** [PostHog/posthog#3592]
## Bug description

The plugin server associated with my instance of PostHog is NOT alive on Heroku, despite the `worker` dyno being active and running for the past many weeks.

## Expected behavior

Plugin server ON.

## How to reproduce

1. Deployed PostHog to Heroku
2. Enabled worker `./bin/docker-worker`

## Environment

I'm running version 1.22.0 of PostHog. Everything else is operational, except "Plugin server alive: NO".

I found this in our logs:

```
2021-03-05T21:24:17.807999+00:00 app[worker.1]: [MAIN] 💥 Launchpad failure! error: no pg_hba.conf entry for host "XXXX", user "XXXX", database "XXXX", SSL off
2021-03-05T21:24:17.808002+00:00 app[worker.1]: at Parser.parseErrorMessage (/app/plugins/node_modules/pg-protocol/dist/parser.js:278:15)
2021-03-05T21:24:17.808002+00:00 app[worker.1]: at Parser.handlePacket (/app/plugins/node_modules/pg-protocol/dist/parser.js:126:29)
2021-03-05T21:24:17.808005+00:00 app[worker.1]: at Parser.parse (/app/plugins/node_modules/pg-protocol/dist/parser.js:39:38)
2021-03-05T21:24:17.808005+00:00 app[worker.1]: at Socket.<anonymous> (/app/plugins/node_modules/pg-protocol/dist/index.js:10:42)
2021-03-05T21:24:17.808006+00:00 app[worker.1]: at Socket.emit (node:events:378:20)
2021-03-05T21:24:17.808007+00:00 app[worker.1]: at Socket.EventEmitter.emit (node:domain:470:12)
2021-03-05T21:24:17.808007+00:00 app[worker.1]: at addChunk (node:internal/streams/readable:313:12)
2021-03-05T21:24:17.808007+00:00 app[worker.1]: at readableAddChunk (node:internal/streams/readable:288:9)
2021-03-05T21:24:17.808008+00:00 app[worker.1]: at Socket.Readable.push (node:internal/streams/readable:227:10)
2021-03-05T21:24:17.808008+00:00 app[worker.1]: at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
2021-03-05T21:24:17.808009+00:00 app[worker.1]: length: 168,
2021-03-05T21:24:17.808010+00:00 app[worker.1]: severity: 'FATAL',
2021-03-05T21:24:17.808010+00:00 app[worker.1]: code: '28000',
2021-03-05T21:24:17.808010+00:00 app[worker.1]: detail: undefined,
2021-03-05T21:24:17.808011+00:00 app[worker.1]: hint: undefined,
2021-03-05T21:24:17.808011+00:00 app[worker.1]: position: undefined,
2021-03-05T21:24:17.808012+00:00 app[worker.1]: internalPosition: undefined,
2021-03-05T21:24:17.808012+00:00 app[worker.1]: internalQuery: undefined,
2021-03-05T21:24:17.808012+00:00 app[worker.1]: where: undefined,
2021-03-05T21:24:17.808013+00:00 app[worker.1]: schema: undefined,
2021-03-05T21:24:17.808014+00:00 app[worker.1]: table: undefined,
2021-03-05T21:24:17.808014+00:00 app[worker.1]: column: undefined,
2021-03-05T21:24:17.808014+00:00 app[worker.1]: dataType: undefined,
2021-03-05T21:24:17.808015+00:00 app[worker.1]: constraint: undefined,
2021-03-05T21:24:17.808015+00:00 app[worker.1]: file: 'auth.c',
2021-03-05T21:24:17.808015+00:00 app[worker.1]: line: '520',
2021-03-05T21:24:17.808016+00:00 app[worker.1]: routine: 'ClientAuthentication'
2021-03-05T21:24:17.808016+00:00 app[worker.1]: }
2021-03-05T21:24:17.813860+00:00 app[worker.1]: [MAIN] 💤  Shutting down gracefully...
```

**Comment by Twixes** [comment]
Hey! If you go to your Heroku app's environment variables, is there a `DEPLOYMENT` var set to `Heroku`? If deployed with our one-click PostHog-on-Heroku option, there should be, otherwise you need to set it yourself. The reason is: Heroku Postgres has a quirk where SSL is required but with slightly unusual different handling (no hostname verification due to the very dynamic way Heroku provisions their data addons) - the env var lets PostHog know to employ that handling.

**Comment by avorio** [comment]
Oh wow, that was a super-obscure setting I wasn't aware of. Adding it seems to have solved the problem.

Thank you very much for the help.

BUT, it looks like I lost all usage data for the past two days and I'm seeing a ton of these errors in the logs now:

```
2021-03-08T02:17:18.217457+00:00 app[worker.1]: [2021-03-08 02:17:18,217: ERROR/MainProcess] Received unregistered task of type 'ee.tasks.webhooks_ee.post_event_to_webhook_ee'.
2021-03-08T02:17:18.217474+00:00 app[worker.1]: The message has been ignored and discarded.
2021-03-08T02:17:18.217476+00:00 app[worker.1]: 
2021-03-08T02:17:18.217503+00:00 app[worker.1]: Did you remember to import the module containing this task?
2021-03-08T02:17:18.217504+00:00 app[worker.1]: Or maybe you're using relative imports?
2021-03-08T02:17:18.217505+00:00 app[worker.1]: 
2021-03-08T02:17:18.217505+00:00 app[worker.1]: Please see
2021-03-08T02:17:18.217506+00:00 app[worker.1]: http://docs.celeryq.org/en/latest/internals/protocol.html
2021-03-08T02:17:18.217506+00:00 app[worker.1]: for more information.
2021-03-08T02:17:18.217507+00:00 app[worker.1]: 
2021-03-08T02:17:18.217510+00:00 app[worker.1]: The full contents of the message body was:
```

What happened to the system during that time? I saw that Redis filled up ... until it crashed.

Is there any way to recover that usage data?

**Comment by Twixes** [comment]
Unfortunately the data can't be recovered if Redis stopped. :( This is an inherent flaw of Redis as an in-memory store and the reason why our VPC/Cloud stack uses Kafka for queuing events instead (but the free version is on Redis due to significantly simpler deployment for users).

Sorry for the experience. We've taken remediation steps to ensure **this never happens again**:
- most immediately, the plugin server now relies on a `DYNO` env var which is set by Heroku by default, instead of our recently added custom `DEPLOYMENT` var (more detailed, but which you unfortunately did not have, as your deployment is from before this addition)
- we've made a point of testing new releases with Heroku instances deployed from months-old repo states then migrated to the latest version (in addition to greenfield deployment) - this in particular would catch this error in advance
- we'll be increasing expiry for events queued in Redis from 1 day to a few days - this wouldn't help in this particular case due to the Redis crash, but will provide better resiliency overall
- lastly, we've fixed the webhook task issue

**Comment by avorio** [comment]
@Twixes Thank you so much for the update, Michael!

I just didn't understand one point: my Redis never crashed. In fact, its store space was adding up and up and up as time went by with the worker not working. And then suddenly, when I added that env var you suggested, all data was wiped out.

**Comment by Twixes** [comment]
Hm, to be honest it's hard to say what caused that without knowing deployment details and what happened exactly.

**Comment by sergioisidoro** [comment]
Would it be possible to document these env variables here: https://posthog.com/docs/self-host/configure/environment-variables?
