### ISSUE TITLE
Error with Redis Cluster (ReplyError: MOVED)

### ISSUE THREAD

**Issue by kilianc** [PostHog/posthog#4694]
## Bug description

I am having trouble making posthog work with a multi master redis cluster configuration.

```
[MAIN] 15:40:54 💥 Launchpad failure! ReplyError: MOVED 854 xxxxxx:29449
    at parseError (/home/posthog/code/plugins/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/posthog/code/plugins/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'get', args: [ '@posthog-plugin-server/mmdb-status' ] }
}
```

I couldn't find a way to pass all the hosts so I just passed one of the masters.

## Expected behavior

No error expected

## How to reproduce

1. Pass one of the hosts as `REDIS_URL`
2. Run `posthog:latest`
3. 💥

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: _please provide_

**Comment by mariusandra** [comment]
If I'm not mistaken, we currently don't support multi-master Redis. I haven't investigated how hard would it be to support this, so I can't promise if or when we could have it. Is this a hard requirement for you?

**Comment by Twixes** [comment]
Unfortunately it'd be quite some work work to support Redis Cluster, because we'd have to use a separate Redis library in Django and also handle this in the plugin server. Definitely doable, but for now using single-master Redis is recommended, and that's what we use at scale too.

**Comment by kilianc** [comment]
I think documenting this would be enough. I managed to get a single node and I am unblocked. I would love HA in the future.
