### ISSUE TITLE
FATAL: sorry, too many clients already

### ISSUE THREAD

**Issue by kilianc** [PostHog/posthog#4709]
## Bug description

It seems like a base installation of posthog requires an high number of connections to postgres, is this configurable? What is the recommended number?

```
⚠️ Piscina worker thread error:
 error: sorry, too many clients already
    at Parser.parseErrorMessage (/home/posthog/code/plugins/node_modules/pg/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/posthog/code/plugins/node_modules/pg/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/posthog/code/plugins/node_modules/pg/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/posthog/code/plugins/node_modules/pg/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:376:20)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 85,
  severity: 'FATAL',
  code: '53300',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'proc.c',
  line: '360',
  routine: 'InitProcess'
}
```
```
[MAIN] 11:30:02 ⚡ @posthog/plugin-server v0.20.1
[MAIN] 11:30:02 ℹ️ 64 workers, 10 tasks per worker
[MAIN] 11:30:02 ✅ Connected to Redis!
[MAIN] 11:30:02 🚶 Connected to job queue producer "graphile"
[MAIN] 11:30:04 🪗 Decompressed GeoLite2-City-2021-06-08.mmdb.br from 22.5 MB into 64.4 MB
[MAIN] 11:30:04 🗺 Starting internal MMDB server...
[MAIN] 11:30:04 👂 Internal MMDB server listening on port 44152
[MAIN] 11:30:04 ⏰ Starting scheduling service...
[___9] 11:30:11 🧵 Starting Piscina worker thread 9…
[___1] 11:30:11 🧵 Starting Piscina worker thread 1…
[___6] 11:30:12 🧵 Starting Piscina worker thread 6…
[___9] 11:30:12 ✅ Connected to Redis!
[___9] 11:30:12 🚶 Connected to job queue producer "graphile"
[__44] 11:30:12 🧵 Starting Piscina worker thread 44…
[__27] 11:30:12 🧵 Starting Piscina worker thread 27…
[___8] 11:30:12 🧵 Starting Piscina worker thread 8…
[___2] 11:30:12 🧵 Starting Piscina worker thread 2…
[__37] 11:30:12 🧵 Starting Piscina worker thread 37…
[__40] 11:30:12 🧵 Starting Piscina worker thread 40…
[__16] 11:30:12 🧵 Starting Piscina worker thread 16…
[__30] 11:30:12 🧵 Starting Piscina worker thread 30…
[__47] 11:30:12 🧵 Starting Piscina worker thread 47…
[___1] 11:30:12 ✅ Connected to Redis!
[___2] 11:30:12 ✅ Connected to Redis!
[__40] 11:30:12 ✅ Connected to Redis!
[__16] 11:30:12 ✅ Connected to Redis!
[__29] 11:30:12 🧵 Starting Piscina worker thread 29…
[__40] 11:30:12 🚶 Connected to job queue producer "graphile"
[__12] 11:30:12 🧵 Starting Piscina worker thread 12…
[__16] 11:30:12 🚶 Connected to job queue producer "graphile"
[__10] 11:30:12 🧵 Starting Piscina worker thread 10…
[___5] 11:30:12 🧵 Starting Piscina worker thread 5…
[___6] 11:30:12 ✅ Connected to Redis!
[__62] 11:30:12 🧵 Starting Piscina worker thread 62…
[__53] 11:30:12 🧵 Starting Piscina worker thread 53…
[__54] 11:30:12 🧵 Starting Piscina worker thread 54…
[__29] 11:30:12 ✅ Connected to Redis!
[___2] 11:30:12 🚶 Connected to job queue producer "graphile"
[___1] 11:30:12 🚶 Connected to job queue producer "graphile"
[__29] 11:30:12 🚶 Connected to job queue producer "graphile"
[__27] 11:30:12 ✅ Connected to Redis!
[MAIN] 11:30:12 ⏰ Starting redlock "plugin-server:locks:schedule" ...
[___3] 11:30:12 🧵 Starting Piscina worker thread 3…
[___4] 11:30:12 🧵 Starting Piscina worker thread 4…
[___5] 11:30:12 ✅ Connected to Redis!
[___6] 11:30:12 🚶 Connected to job queue producer "graphile"
[___8] 11:30:12 ✅ Connected to Redis!
[__10] 11:30:12 ✅ Connected to Redis!
[__11] 11:30:12 🧵 Starting Piscina worker thread 11…
[__24] 11:30:12 🧵 Starting Piscina worker thread 24…
[__27] 11:30:12 🚶 Connected to job queue producer "graphile"
[__28] 11:30:12 🧵 Starting Piscina worker thread 28…
[__37] 11:30:12 ✅ Connected to Redis!
[__38] 11:30:12 🧵 Starting Piscina worker thread 38…
[__39] 11:30:12 🧵 Starting Piscina worker thread 39…
[__44] 11:30:12 ✅ Connected to Redis!
[__48] 11:30:12 🧵 Starting Piscina worker thread 48…
[__53] 11:30:12 ✅ Connected to Redis!
[___5] 11:30:12 🚶 Connected to job queue producer "graphile"
[__53] 11:30:12 🚶 Connected to job queue producer "graphile"
[MAIN] 11:30:12 ✅ Connected to Redis!
[___8] 11:30:12 🚶 Connected to job queue producer "graphile"
[__10] 11:30:12 🚶 Connected to job queue producer "graphile"
[__22] 11:30:12 🧵 Starting Piscina worker thread 22…
[__23] 11:30:12 🧵 Starting Piscina worker thread 23…
[__44] 11:30:12 🚶 Connected to job queue producer "graphile"
[MAIN] 11:30:12 🔄 Starting job queue consumer, trying to get lock...
[MAIN] 11:30:12 ⏰ Starting redlock "plugin-server:locks:job-queue-consumer" ...
[___3] 11:30:12 ✅ Connected to Redis!
[___7] 11:30:12 🧵 Starting Piscina worker thread 7…
[__11] 11:30:12 ✅ Connected to Redis!
[__15] 11:30:12 🧵 Starting Piscina worker thread 15…
[__18] 11:30:12 🧵 Starting Piscina worker thread 18…
[__38] 11:30:12 ✅ Connected to Redis!
[__39] 11:30:12 ✅ Connected to Redis!
[__41] 11:30:12 🧵 Starting Piscina worker thread 41…
[__50] 11:30:12 🧵 Starting Piscina worker thread 50…
[__28] 11:30:12 ✅ Connected to Redis!
[__39] 11:30:12 🚶 Connected to job queue producer "graphile"
[___4] 11:30:12 ✅ Connected to Redis!
[__47] 11:30:12 ✅ Connected to Redis!
[__38] 11:30:12 🚶 Connected to job queue producer "graphile"
[__57] 11:30:12 🧵 Starting Piscina worker thread 57…
[MAIN] 11:30:12 ✅ Connected to Redis!
[MAIN] 11:30:12 🔒 Redlock "plugin-server:locks:schedule" acquired!
[MAIN] 11:30:12 🍆 Starting Celery worker...
[MAIN] 11:30:12 ✅ Celery worker subscribed to posthog.tasks.process_event.process_event_with_plugins!
[___3] 11:30:13 🚶 Connected to job queue producer "graphile"
[__12] 11:30:13 ✅ Connected to Redis!
[__13] 11:30:12 🧵 Starting Piscina worker thread 13…
[__26] 11:30:12 🧵 Starting Piscina worker thread 26…
[__28] 11:30:12 🚶 Connected to job queue producer "graphile"
[__30] 11:30:12 ✅ Connected to Redis!
[__37] 11:30:12 🚶 Connected to job queue producer "graphile"
[__48] 11:30:12 ✅ Connected to Redis!
[MAIN] 11:30:13 🔒 Redlock "plugin-server:locks:job-queue-consumer" acquired!
[MAIN] 11:30:13 🔄 Job queue consumer lock aquired
[MAIN] 11:30:13 ✅ Connected to Redis!
[___4] 11:30:13 🚶 Connected to job queue producer "graphile"
[__11] 11:30:13 🚶 Connected to job queue producer "graphile"
[__12] 11:30:13 🚶 Connected to job queue producer "graphile"
[__15] 11:30:13 ✅ Connected to Redis!
[__18] 11:30:13 ✅ Connected to Redis!
[__22] 11:30:13 ✅ Connected to Redis!
[__23] 11:30:13 ✅ Connected to Redis!
[__41] 11:30:13 ✅ Connected to Redis!
[__47] 11:30:13 🚶 Connected to job queue producer "graphile"
[__54] 11:30:13 ✅ Connected to Redis!
[__22] 11:30:13 🚶 Connected to job queue producer "graphile"
[__62] 11:30:13 ✅ Connected to Redis!
[MAIN] 11:30:13 🚀 All systems go
[___7] 11:30:13 ✅ Connected to Redis!
[__15] 11:30:13 🚶 Connected to job queue producer "graphile"
[__18] 11:30:13 🚶 Connected to job queue producer "graphile"
[__30] 11:30:13 🚶 Connected to job queue producer "graphile"
[__31] 11:30:13 🧵 Starting Piscina worker thread 31…
[__32] 11:30:13 🧵 Starting Piscina worker thread 32…
[__41] 11:30:13 🚶 Connected to job queue producer "graphile"
[__57] 11:30:13 ✅ Connected to Redis!
[__59] 11:30:13 🧵 Starting Piscina worker thread 59…
[__61] 11:30:13 🧵 Starting Piscina worker thread 61…
[__13] 11:30:13 ✅ Connected to Redis!
[__23] 11:30:13 🚶 Connected to job queue producer "graphile"
[__24] 11:30:13 ✅ Connected to Redis!
[__26] 11:30:13 ✅ Connected to Redis!
[__48] 11:30:13 🚶 Connected to job queue producer "graphile"
[__54] 11:30:13 🚶 Connected to job queue producer "graphile"
[__56] 11:30:13 🧵 Starting Piscina worker thread 56…
[__57] 11:30:13 🚶 Connected to job queue producer "graphile"
[__63] 11:30:13 🧵 Starting Piscina worker thread 63…
[___7] 11:30:13 🚶 Connected to job queue producer "graphile"
[__13] 11:30:13 🚶 Connected to job queue producer "graphile"
[core] INFO: Worker connected and looking for jobs... (task names: 'pluginJob')
[__19] 11:30:13 🧵 Starting Piscina worker thread 19…
[__25] 11:30:13 🧵 Starting Piscina worker thread 25…
[__64] 11:30:13 🧵 Starting Piscina worker thread 64…
[__62] 11:30:13 🚶 Connected to job queue producer "graphile"
[__36] 11:30:13 🧵 Starting Piscina worker thread 36…
[__50] 11:30:13 ✅ Connected to Redis!
[__14] 11:30:13 🧵 Starting Piscina worker thread 14…
[__26] 11:30:13 🚶 Connected to job queue producer "graphile"
[__49] 11:30:13 🧵 Starting Piscina worker thread 49…
[__17] 11:30:13 🧵 Starting Piscina worker thread 17…
[__59] 11:30:13 ✅ Connected to Redis!
[__24] 11:30:13 🚶 Connected to job queue producer "graphile"
[__34] 11:30:13 🧵 Starting Piscina worker thread 34…
[__43] 11:30:13 🧵 Starting Piscina worker thread 43…
[__33] 11:30:13 🧵 Starting Piscina worker thread 33…
[__46] 11:30:13 🧵 Starting Piscina worker thread 46…
[__21] 11:30:13 🧵 Starting Piscina worker thread 21…
[__42] 11:30:13 🧵 Starting Piscina worker thread 42…
[__63] 11:30:13 ✅ Connected to Redis!
[__61] 11:30:13 ✅ Connected to Redis!
[__50] 11:30:13 🚶 Connected to job queue producer "graphile"
[__56] 11:30:13 ✅ Connected to Redis!
[__52] 11:30:13 🧵 Starting Piscina worker thread 52…
[__59] 11:30:13 🚶 Connected to job queue producer "graphile"
[__51] 11:30:13 🧵 Starting Piscina worker thread 51…
[__35] 11:30:13 🧵 Starting Piscina worker thread 35…
[__20] 11:30:13 🧵 Starting Piscina worker thread 20…
[__14] 11:30:13 ✅ Connected to Redis!
[__45] 11:30:13 🧵 Starting Piscina worker thread 45…
[__64] 11:30:13 ✅ Connected to Redis!
[__55] 11:30:13 🧵 Starting Piscina worker thread 55…
[__14] 11:30:13 🚶 Connected to job queue producer "graphile"
[__61] 11:30:13 🚶 Connected to job queue producer "graphile"
[__43] 11:30:13 ✅ Connected to Redis!
[__56] 11:30:13 🚶 Connected to job queue producer "graphile"
[__46] 11:30:13 ✅ Connected to Redis!
[__63] 11:30:13 🚶 Connected to job queue producer "graphile"
[__60] 11:30:13 🧵 Starting Piscina worker thread 60…
[__42] 11:30:13 ✅ Connected to Redis!
[__52] 11:30:13 ✅ Connected to Redis!
[__31] 11:30:13 ✅ Connected to Redis!
[__58] 11:30:13 🧵 Starting Piscina worker thread 58…
[__32] 11:30:13 ✅ Connected to Redis!
[__45] 11:30:13 ✅ Connected to Redis!
[__64] 11:30:13 🚶 Connected to job queue producer "graphile"
[__43] 11:30:13 🚶 Connected to job queue producer "graphile"
[__19] 11:30:13 ✅ Connected to Redis!
[__25] 11:30:13 ✅ Connected to Redis!
[__42] 11:30:13 🚶 Connected to job queue producer "graphile"
[__46] 11:30:13 🚶 Connected to job queue producer "graphile"
[__36] 11:30:13 ✅ Connected to Redis!
[__45] 11:30:13 🚶 Connected to job queue producer "graphile"
[__49] 11:30:13 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__52] 11:30:13 🚶 Connected to job queue producer "graphile"
[__31] 11:30:13 🚶 Connected to job queue producer "graphile"
[__32] 11:30:13 🚶 Connected to job queue producer "graphile"
[__17] 11:30:13 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__34] 11:30:13 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__21] 11:30:13 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__49] 11:30:13 ✅ Connected to Redis!
[__33] 11:30:13 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__17] 11:30:13 ✅ Connected to Redis!
[__51] 11:30:13 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__34] 11:30:13 ✅ Connected to Redis!
[__21] 11:30:13 ✅ Connected to Redis!
[__25] 11:30:13 🚶 Connected to job queue producer "graphile"
[__33] 11:30:13 ✅ Connected to Redis!
[__19] 11:30:13 🚶 Connected to job queue producer "graphile"
[__35] 11:30:13 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__36] 11:30:13 🚶 Connected to job queue producer "graphile"
[__20] 11:30:13 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__55] 11:30:13 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__51] 11:30:13 ✅ Connected to Redis!
[__35] 11:30:13 ✅ Connected to Redis!
[__55] 11:30:13 ✅ Connected to Redis!
[__20] 11:30:13 ✅ Connected to Redis!
[__58] 11:30:13 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__60] 11:30:13 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__58] 11:30:13 ✅ Connected to Redis!
[__60] 11:30:13 ✅ Connected to Redis!
[MAIN] 11:30:15 ✅ Connected to Redis!
[__70] 11:30:15 🧵 Starting Piscina worker thread 70…
[__74] 11:30:15 🧵 Starting Piscina worker thread 74…
[__70] 11:30:15 ✅ Connected to Redis!
[__76] 11:30:15 🧵 Starting Piscina worker thread 76…
[__74] 11:30:15 ✅ Connected to Redis!
[__70] 11:30:15 🚶 Connected to job queue producer "graphile"
[__73] 11:30:15 🧵 Starting Piscina worker thread 73…
[__71] 11:30:15 🧵 Starting Piscina worker thread 71…
[__76] 11:30:15 ✅ Connected to Redis!
[__74] 11:30:15 🚶 Connected to job queue producer "graphile"
[__73] 11:30:15 ✅ Connected to Redis!
[__80] 11:30:15 🧵 Starting Piscina worker thread 80…
[__73] 11:30:15 🚶 Connected to job queue producer "graphile"
[__71] 11:30:15 ✅ Connected to Redis!
[__80] 11:30:15 ✅ Connected to Redis!
[__76] 11:30:15 🚶 Connected to job queue producer "graphile"
[__71] 11:30:15 🚶 Connected to job queue producer "graphile"
[__80] 11:30:15 🚶 Connected to job queue producer "graphile"
[__78] 11:30:15 🧵 Starting Piscina worker thread 78…
[__82] 11:30:15 🧵 Starting Piscina worker thread 82…
[__68] 11:30:15 🧵 Starting Piscina worker thread 68…
[__77] 11:30:15 🧵 Starting Piscina worker thread 77…
[__65] 11:30:15 🧵 Starting Piscina worker thread 65…
[__79] 11:30:15 🧵 Starting Piscina worker thread 79…
[__69] 11:30:15 🧵 Starting Piscina worker thread 69…
[__78] 11:30:15 ✅ Connected to Redis!
[__68] 11:30:15 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__82] 11:30:15 ✅ Connected to Redis!
[__68] 11:30:15 ✅ Connected to Redis!
[__78] 11:30:15 🚶 Connected to job queue producer "graphile"
[__82] 11:30:15 🚶 Connected to job queue producer "graphile"
[__79] 11:30:15 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__77] 11:30:15 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__75] 11:30:15 🧵 Starting Piscina worker thread 75…
[__69] 11:30:15 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__65] 11:30:15 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__66] 11:30:15 🧵 Starting Piscina worker thread 66…
[__79] 11:30:15 ✅ Connected to Redis!
[__77] 11:30:15 ✅ Connected to Redis!
[__69] 11:30:15 ✅ Connected to Redis!
[__65] 11:30:15 ✅ Connected to Redis!
[__67] 11:30:15 🧵 Starting Piscina worker thread 67…
[__84] 11:30:15 🧵 Starting Piscina worker thread 84…
[__66] 11:30:15 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__75] 11:30:15 ✅ Connected to Redis!
[__66] 11:30:15 ✅ Connected to Redis!
[__67] 11:30:15 ✅ Connected to Redis!
[__75] 11:30:15 🚶 Connected to job queue producer "graphile"
[__84] 11:30:15 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__67] 11:30:15 🚶 Connected to job queue producer "graphile"
[__84] 11:30:15 ✅ Connected to Redis!
[__72] 11:30:15 🧵 Starting Piscina worker thread 72…
[__83] 11:30:15 🧵 Starting Piscina worker thread 83…
[__81] 11:30:15 🧵 Starting Piscina worker thread 81…
[__72] 11:30:15 ✅ Connected to Redis!
[__72] 11:30:15 🚶 Connected to job queue producer "graphile"
[__81] 11:30:15 ✅ Connected to Redis!
[__83] 11:30:15 🟡 Can not start job queue producer "graphile": sorry, too many clients already
[__83] 11:30:15 ✅ Connected to Redis!
[__81] 11:30:15 🚶 Connected to job queue producer "graphile"

```
## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
@kilianc can you give a bit of context on how you're deploying/running posthog? What version, which platform, etc.

**Comment by mariusandra** [comment]
This seems connected to the case we had, when aurora ran out of connections. Somehow the plugin server's job queue is not pooling them well.

**Comment by neilkakkar** [comment]
Hmm, we have 1 pool per thread (maybe this is why?) - and 80 threads => 80 pools, which is a lot of threads. By default, this is the number of cores, but you can configure this using the `WORKER_CONCURRENCY` env variable.

I think perhaps we should have the threads share the pool?

**Comment by mariusandra** [comment]
It does make sense to have one queue/export per server, not per worker. Unfortunately we don't really have a worker->main communication channel right now, other than just task replies. Such a channel would solve many other issues though, so might be worth prioritising 🤔

**Comment by mariusandra** [comment]
@kilianc could it be an option for you to put `pgbouncer` between posthog and postgres? That solved the issue for us at least.

**Comment by neilkakkar** [comment]
Actually, correction: every thread right now has 2 pools: 1 to connect directly to Postgres, another 1 via the graphileQueue pool.

Reusing the pool is probably possible without establishing a separate worker->main communication channel. What other issues does this communication solve? 🤔

**Comment by mariusandra** [comment]
We currently have a TCP server running on the main thread for the GeoIP plugin. This could move to a better/internal communication model. Sending the plugin schedule to the main thread is something that could happen async without us explicitly asking for it.

The kafka producer, other job queues (S3), etc could then also live on the main thread and just pass messages received from the worker threads.

Many such things :)

**Comment by mhensley-cls** [comment]
```


2021-08-16 09:24:42 | The above exception was the direct cause of the following exception:
-- | --
  |   | 2021-08-16 09:24:42 |  
  |   | 2021-08-16 09:24:42 |  
  |   | 2021-08-16 09:24:42 | psycopg2.OperationalError: FATAL:  sorry, too many clients already
  |   | 2021-08-16 09:24:42 | conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  |   | 2021-08-16 09:24:42 | File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
  |   | 2021-08-16 09:24:42 | connection = Database.connect(**conn_params)
  |   | 2021-08-16 09:24:42 | File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
  |   | 2021-08-16 09:24:42 | return func(*args, **kwargs)
  |   | 2021-08-16 09:24:42 | File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
  |   | 2021-08-16 09:24:42 | self.connection = self.get_new_connection(conn_params)
  |   | 2021-08-16 09:24:42 | File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
  |   | 2021-08-16 09:24:42 | return func(*args, **kwargs)
  |   | 2021-08-16 09:24:42 | File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
  |   | 2021-08-16 09:24:42 | self.connect()
  |   | 2021-08-16 09:24:42 | File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
  |   | 2021-08-16 09:24:42 | Traceback (most recent call last):
  |   | 2021-08-16 09:24:42 | Internal Server Error: /

```
We are getting this on the web component.

**Comment by timgl** [comment]
@mhensley-cls Hey, this might be a slightly different issue to the rest of the thread. How did you deploy PostHog (provider, helm chart (which) etc?) and how many instances of the web/plugin server are you running? Depending on the setup you may need to add PGBouncer

**Comment by mhensley-cls** [comment]
@timgl - running a pretty standard helm deployment. I'll check with my team about pg-bouncer.

![image](https://user-images.githubusercontent.com/76120104/129577954-e6c88e93-0f89-44a4-86b0-f104f8010c5b.png)

**Comment by fuziontech** [comment]
@mhensley-cls - Do you know what helm chart version you are running? It should be running pgbouncer by default for graphile and for posthog. That will definitely resolve any issues around running out of connections to Postgres.

https://github.com/PostHog/charts-clickhouse/blob/main/charts/posthog/templates/pgbouncer-service.yaml

**Comment by paolodamico** [comment]
Hey @kilianc, I'm closing this issue as it looks like it may be solved, particularly with the new app updates. Let us know if you keep running into other issues.
