### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by avorio** [PostHog/posthog#5176]
## Bug description

Suddenly, out of nowhere, I'm getting an ugly Server Error (500) when trying to access our Heroku-hosted instance of PostHog. How best to recover from this, apart from increasing Redis' memory?

## Environment

- Heroku
- PostHog v1.26.0

## Additional context

```
16 Jul 2021 13:39:42.771128 <190>1 2021-07-16T16:39:42.697566+00:00 app web.1 - - Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/kombu/connection.py", line 439, in _reraise_as_library_errors
    yield
  File "/app/.heroku/python/lib/python3.8/site-packages/kombu/connection.py", line 518, in _ensured
    return fun(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/kombu/messaging.py", line 194, in _publish
    [maybe_declare(entity) for entity in declare]
  File "/app/.heroku/python/lib/python3.8/site-packages/kombu/messaging.py", line 194, in <listcomp>
    [maybe_declare(entity) for entity in declare]
  File "/app/.heroku/python/lib/python3.8/site-packages/kombu/messaging.py", line 102, in maybe_declare
    return maybe_declare(entity, self.channel, retry, **retry_policy)
  File "/app/.heroku/python/lib/python3.8/site-packages/kombu/common.py", line 121, in maybe_declare
    return _maybe_declare(entity, channel)
  File "/app/.heroku/python/lib/python3.8/site-packages/kombu/common.py", line 161, in _maybe_declare
    entity.declare(channel=channel)
  File "/app/.heroku/python/lib/python3.8/site-packages/kombu/entity.py", line 609, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/app/.heroku/python/lib/python3.8/site-packages/kombu/entity.py", line 618, in _create_queue
    self.queue_declare(nowait=nowait, passive=False, channel=channel)
  File "/app/.heroku/python/lib/python3.8/site-packages/kombu/entity.py", line 646, in queue_declare
    ret = channel.queue_declare(
  File "/app/.heroku/python/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 532, in queue_declare
    return queue_declare_ok_t(queue, self._size(queue), 0)
  File "/app/.heroku/python/lib/python3.8/site-packages/kombu/transport/redis.py", line 775, in _size
    sizes = pipe.execute()
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/client.py", line 3967, in execute
    return execute(conn, stack, raise_on_error)
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/client.py", line 3865, in _execute_transaction
    raise errors[0][1]
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/client.py", line 3852, in _execute_transaction
    self.parse_response(connection, '_')
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/client.py", line 3925, in parse_response
    result = Redis.parse_response(
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 752, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (LLEN posthog-plugins) of pipeline caused error: OOM command not allowed when used memory > 'maxmemory'.
```

**Comment by avorio** [comment]
I was inspecting our logs further and noticed some weird stuff, too:

```
09 Jul 2021 14:23:17.303138 <190>1 2021-07-09T17:23:16.705994+00:00 app worker.1 - - Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/app/plugins/node_modules/pg/lib/client.js:132:73)Exception
09 Jul 2021 14:23:17.303143 <190>1 2021-07-09T17:23:16.705996+00:00 app worker.1 - - at Object.onceWrapper (node:events:513:28)
09 Jul 2021 14:23:17.303140 <190>1 2021-07-09T17:23:16.705996+00:00 app worker.1 - - at Connection.emit (node:events:394:28)
09 Jul 2021 14:23:17.303140 <190>1 2021-07-09T17:23:16.705997+00:00 app worker.1 - - at Connection.emit (node:domain:470:12)
09 Jul 2021 14:23:17.303181 <190>1 2021-07-09T17:23:16.705997+00:00 app worker.1 - - at TLSSocket.<anonymous> (/app/plugins/node_modules/pg/lib/connection.js:107:12)
09 Jul 2021 14:23:17.303139 <190>1 2021-07-09T17:23:16.705997+00:00 app worker.1 - - at TLSSocket.emit (node:events:406:35)
09 Jul 2021 14:23:17.303139 <190>1 2021-07-09T17:23:16.705998+00:00 app worker.1 - - at TLSSocket.emit (node:domain:470:12)
09 Jul 2021 14:23:17.303158 <190>1 2021-07-09T17:23:16.705998+00:00 app worker.1 - - at endReadableNT (node:internal/streams/readable:1329:12)
09 Jul 2021 14:23:17.303171 <190>1 2021-07-09T17:23:16.705999+00:00 app worker.1 - - at processTicksAndRejections (node:internal/process/task_queues:83:21)
09 Jul 2021 14:23:17.303138 <190>1 2021-07-09T17:23:16.706695+00:00 app worker.1 - - Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/app/plugins/node_modules/pg/lib/client.js:132:73)Exception
09 Jul 2021 14:23:17.303143 <190>1 2021-07-09T17:23:16.706696+00:00 app worker.1 - - at Object.onceWrapper (node:events:513:28)
09 Jul 2021 14:23:17.303140 <190>1 2021-07-09T17:23:16.706696+00:00 app worker.1 - - at Connection.emit (node:events:394:28)
09 Jul 2021 14:23:17.303140 <190>1 2021-07-09T17:23:16.706697+00:00 app worker.1 - - at Connection.emit (node:domain:470:12)
09 Jul 2021 14:23:17.303181 <190>1 2021-07-09T17:23:16.706697+00:00 app worker.1 - - at TLSSocket.<anonymous> (/app/plugins/node_modules/pg/lib/connection.js:107:12)
09 Jul 2021 14:23:17.303139 <190>1 2021-07-09T17:23:16.706697+00:00 app worker.1 - - at TLSSocket.emit (node:events:406:35)
09 Jul 2021 14:23:17.303139 <190>1 2021-07-09T17:23:16.706697+00:00 app worker.1 - - at TLSSocket.emit (node:domain:470:12)
09 Jul 2021 14:23:17.303158 <190>1 2021-07-09T17:23:16.706698+00:00 app worker.1 - - at endReadableNT (node:internal/streams/readable:1329:12)
09 Jul 2021 14:23:17.303171 <190>1 2021-07-09T17:23:16.706698+00:00 app worker.1 - - at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by paolodamico** [comment]
Tagging @liyiy here for help

**Comment by liyiy** [comment]
Hi there, has upgrading to the newest release helped/are you still encountering this issue?

**Comment by paolodamico** [comment]
Seems like this is no longer an issue, feel free to reopen if this is not the case @avorio
