### ISSUE TITLE
INCLUDE_DOCS env break app

### ISSUE THREAD

**Issue by maximmarakov** [PostHog/posthog#574]
If env var "INCLUDE_DOCS" set True , then docker container fail with:
```python
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'drf_yasg'
```

**Comment by SanketDG** [comment]
Seems because of https://github.com/PostHog/posthog/blob/master/preview.Dockerfile#L30, maybe this should be removed as it makes sense to have API docs generated during dev.

**Comment by timgl** [comment]
Yeah these docs are not very useful TBH - I only added them as a test. I'd be in favour of removing them completely. We can then replace them with our own docs at docs.posthog.com

**Comment by SanketDG** [comment]
@timgl 

> I'd be in favour of removing them completely. We can then replace them with our own docs at docs.posthog.com

Should I go ahead and remove those?

**Comment by timgl** [comment]
@SanketDG That'd be aweomse!
