### ISSUE TITLE
Add (DAU) to hover if graph is filtered on DAU

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#609]
**Is your feature request related to a problem? Please describe.**
When hovering over the graph it's not clear whether the event shows total volume of DAU

![image](https://user-images.githubusercontent.com/1727427/79466728-dd505a80-7ff4-11ea-84b7-563cd6f2906f.png)

**Describe the solution you'd like**

Show `(DAU)` next to event

**Comment by abhijitghate** [comment]
Hey @timgl ! I wish to contribute to PostHog. I picked this issue to go on. I did the setup as per instructions here - https://posthog.com/docs/developing-locally#using-virtualenv 
But I am getting an error which says 

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/setup_admin

Django Version: 3.0.6
Python Version: 3.6.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'posthog.apps.PostHogConfig',
 'rest_framework',
 'loginas',
 'corsheaders',
 'social_django',
 'debug_toolbar']
Installed Middleware:
['posthog.middleware.SameSiteSessionMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'posthog.middleware.AllowIP',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']

Template loader postmortem
Django tried loading these templates, in this order:

Using engine django:
    * django.template.loaders.filesystem.Loader: /home/abhijit/Documents/posthog/posthog/frontend/dist/layout.html (Source does not exist)
    * django.template.loaders.filesystem.Loader: /home/abhijit/Documents/posthog/posthog/posthog/templates/layout.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/contrib/admin/templates/layout.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/contrib/auth/templates/layout.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /home/abhijit/Documents/posthog/posthog/posthog/templates/layout.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/rest_framework/templates/layout.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/loginas/templates/layout.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/debug_toolbar/templates/layout.html (Source does not exist)


Template error:
In template /home/abhijit/Documents/posthog/posthog/posthog/templates/setup_admin.html, error at line 1
   layout.html
   1 :  {% extends 'layout.html' %} 
   2 : 
   3 : {% block content %}
   4 :     <form class="form-signin" method="post" action="/setup_admin">
   5 :         {% csrf_token %}
   6 :         <h1 class="h3 mb-3 font-weight-normal">Create PostHog account</h1>
   7 : 
   8 :         {% if error %}
   9 :         <p>That account already exists. <a href='/login'>Try logging in?</a>.</p>
   10 :         {% endif %}
   11 :         {% if invalid_input %}


Traceback (most recent call last):
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/test/utils.py", line 95, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/template/loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/template/engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)

The above exception (layout.html) was the direct cause of the following exception:
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/abhijit/Documents/posthog/posthog/posthog/urls.py", line 106, in setup_admin
    return render_template("setup_admin.html", request)
  File "/home/abhijit/Documents/posthog/posthog/posthog/utils.py", line 111, in render_template
    html = template.render(context, request=request)
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/abhijit/Documents/posthog/posthog/env/lib/python3.6/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc

Exception Type: TemplateDoesNotExist at /setup_admin
Exception Value: layout.html
```

Have I missed something in setting the project up?

**Comment by timgl** [comment]
@abhijitghate Hi! Could you try running `python manage.py collectstatic`?

**Comment by abhijitghate** [comment]
@timgl  Hey! Thanks for replying. I did run that already. But I am getting the same error.

**Comment by timgl** [comment]
Are you running `bin/start`? Is there a `frontend/dist/layout.html` file? You might actually have to wait until the frontend is completely built before layout.html shows up

**Comment by abhijitghate** [comment]
Oh yes @timgl ! I got it running. I ran frontend separetely and waited for build to complete! Thanks!:)

**Comment by abhijitghate** [comment]
Hey @timgl I have made a PR for this issue. Please have a look. 
Here it is - https://github.com/PostHog/posthog/pull/1201
