### ISSUE TITLE
team_id field not validated in /api/event

### ISSUE THREAD

**Issue by tirkarthi** [PostHog/posthog#6114]
## Bug description

It seems team_id is not validated in the payload for /api/event and absence of the field causes database level error.

## Expected behavior

A validation error message should be thrown.

## How to reproduce

```
curl -X POST http://localhost:8000/api/event/ -H "Authorization:Bearer e2e_demo_api_key" -H "Content-Type: application/json" -d '{"distinct_id": 1}'
```
Error : 

```
Internal Server Error: /api/event/
Traceback (most recent call last):
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "team_id" of relation "posthog_event" violates not-null constraint
DETAIL:  Failing row contains (964, null, {}, [], 2021-09-27 11:16:12.057226+00, null, 1, null, 2021-09-27 11:16:12.057617+00, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/karthikeyan/stuff/python/posthog/posthog/models/event.py", line 273, in create
    if kwargs.get("elements"):
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "team_id" of relation "posthog_event" violates not-null constraint
DETAIL:  Failing row contains (964, null, {}, [], 2021-09-27 11:16:12.057226+00, null, 1, null, 2021-09-27 11:16:12.057617+00, null).

Internal Server Error: /api/event/
Traceback (most recent call last):
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "team_id" of relation "posthog_event" violates not-null constraint
DETAIL:  Failing row contains (964, null, {}, [], 2021-09-27 11:16:12.057226+00, null, 1, null, 2021-09-27 11:16:12.057617+00, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/karthikeyan/stuff/python/posthog/posthog/models/event.py", line 273, in create
    if kwargs.get("elements"):
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/karthikeyan/stuff/python/posthog/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "team_id" of relation "posthog_event" violates not-null constraint
DETAIL:  Failing row contains (964, null, {}, [], 2021-09-27 11:16:12.057226+00, null, 1, null, 2021-09-27 11:16:12.057617+00, null).

"POST /api/event/ HTTP/1.1" 500 230167
"POST /api/event/ HTTP/1.1" 500 230167

```

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by Twixes** [comment]
This should be resolved by #6068 that will be merged soon

**Comment by tirkarthi** [comment]
I guess the linked PR solves a different issue over authorization and that this issue is a separate issue regarding serializer level validation used for creation. I checked out the PR locally and I am still able to reproduce the error. Please let me know if I am missing something.

```
posthog git:(4263-restrictions) curl -o /dev/null -s -w "%{http_code}\n" -X POST http://localhost:8000/api/event/ -H "Authorization:Bearer e2e_demo_api_key" -H "Content-Type: application/json" -d '{"distinct_id": 1, "team_id": 1}' 
500

```

**Comment by Twixes** [comment]
Oh, you're correct. I missed that this is a `POST` request! This is still a bug, but in a bit of a different way – `POST` requests are not actually supported for `/api/event`. All event writes should instead go to the capture route `/capture` (alias: `/e`). Created https://github.com/PostHog/posthog/pull/6169 to disable non-read actions on `/api/event`.
