### ISSUE TITLE
StoryBook cannot load events or funnels scenes

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#6138]
## Bug description

Storybook cannot load the events or funnels scenes.

something in #6079  has broken storybook for the events pages

But, if I checkout 9315a0d7 (the commit before) then the storybook page for events works but the funnels page shows the same error

```
history[method] is not a function
TypeError: history[method] is not a function
    at updateLocation (http://localhost:6006/vendors~main.iframe.bundle.js:318723:38)
    at http://localhost:6006/vendors~main.iframe.bundle.js:320813:26
    at Object.dispatch (http://localhost:6006/vendors~main.iframe.bundle.js:320888:19)
    at Object.logic.actions.<computed> [as replace] (http://localhost:6006/vendors~main.iframe.bundle.js:319980:35)
    at listeners.<computed> (http://localhost:6006/vendors~main.iframe.bundle.js:319285:60)
    at http://localhost:6006/vendors~main.iframe.bundle.js:320813:26
    at Object.dispatch (http://localhost:6006/vendors~main.iframe.bundle.js:320888:19)
    at Object.logic.actions.<computed> [as setFilters] (http://localhost:6006/vendors~main.iframe.bundle.js:319980:35)
    at Object.insights [as action] (http://localhost:6006/main.iframe.bundle.js:38343:19)
    at listeners.<computed> (http://localhost:6006/vendors~main.iframe.bundle.js:319265:62)
```

<img width="1439" alt="Screenshot 2021-09-28 at 08 50 55" src="https://user-images.githubusercontent.com/984817/135046057-8770c171-30bb-458c-959e-34e2835def01.png">

I think it's "in" kea router

```
sharedListeners: ({ actions }) => ({
    updateLocation: ({ url, searchInput, hashInput }, breakpoint, action) => {
      const method: 'push' | 'replace' = action.type === actions.push.toString() ? 'push' : 'replace'
      const { history } = getRouterContext()
      const response = combineUrl(url, searchInput, hashInput)

      history[`${method}State` as 'pushState' | 'replaceState']({}, '', response.url)
      actions.locationChanged({ method: method.toUpperCase() as 'PUSH' | 'REPLACE', ...response })
    },
  }),
```

This line `history[`${method}State` as 'pushState' | 'replaceState']({}, '', response.url)` expects that the history loaded from `getRouterContext` has a `pushState` and a `replaceState` method

`window.history` has `pushState` and `replaceState` but the `MemoryHistory` [created here](https://github.com/PostHog/posthog/blob/master/frontend/src/lib/storybook/kea-story.tsx#L9) has `push` and `replace` (I think all react-router `history`s have push and replace.

That `MemoryHistory` is injected. So if any of the loaded scenes pushes or replaces states then kea-router throws because the injected `MemoryHistory` doesn't have the expected methods.

I'm not sure if this is a bug with kea-router or our use

## Expected behavior

It works :)

## How to reproduce

1. checkout a commit before #6079 e.g. 9315a0d7
2. run `yarn storybook`
3. navigate to events
4. see that it works
5. checkout master
6. run `yarn storybook`
7. navigate to events
8. see that it does not

## Environment

N/A

**Comment by pauldambra** [comment]
@mariusandra I thought you'd understand kea-router enough to say if this is a problem with how we use it or not

**Comment by mariusandra** [comment]
Hey, it feels like MemoryHistory is being the bad apple here. `pushState` is a [very valid method](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState) on the history object. That's the one the router should call. The memory history is somehow not following the spec here. 

I had to do [something like this](https://github.com/PostHog/posthog/blob/ef70592603d316f20281cbe10d313d145c92736c/frontend/src/test/kea-test-utils/init.ts#L33-36) to get tests working when I had the same issue.
