### ISSUE TITLE
Hobby script doesn't work

### ISSUE THREAD

**Issue by raphaeltm** [PostHog/posthog#7690]
## Bug description

I ran the hobby script on a DigitalOcean VM, but a few things failed which led to a completely non-functional deployment. Details on resolution below.

## Expected behavior

The hobby deploy script should just work.

## How to reproduce

1. Start a VM (though I assume the same problem would arise anywhere)
2. Run ` /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)" ` (currently at commit `b3ba889`)

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: Hobby deploy script is from commit `b56b141`
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

When web service starts we get:
`/compose/start: line 2: ./bin/migrate: No such file or directory` 

From what I can see, it should probably be `./bin/docker-migrate`. I ran `docker-compose -f docker-compose.hobby.yml exec web ./bin/docker-migrate` and that seemed to do the trick.

Since the worker depends on the tables created by the web service, we have to run `docker-compose -f docker-compose.hobby.yml restart worker` 

Okay, now we've got a happy preflight check, but as soon as we login we start to get other errors, like this one:

<img width="352" alt="Screen Shot 2021-12-13 at 11 56 54" src="https://user-images.githubusercontent.com/910895/145879512-6611930e-83b6-49dd-9b10-89f7d143d8fe.png">

Looking at the logs, I figured this was probably related:

```
worker_1      | [2021-12-13 19:56:50,905: ERROR/ForkPoolWorker-1] Task posthog.celery.clickhouse_mutation_count[ce39a58b-7204-4cb4-af4f-9bcff17bf951] raised unexpected: ServerException("DB::Exception: Database `posthog` doesn't exist. Stack trace:\n\n0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8b6cbba in /usr/bin/clickhouse\n1. DB::TCPHandler::runImpl() @ 0x104305e4 in /usr/bin/clickhouse\n2. DB::TCPHandler::run() @ 0x10441839 in /usr/bin/clickhouse\n3. Poco::Net::TCPServerConnection::start() @ 0x12a3fd4f in /usr/bin/clickhouse\n4. Poco::Net::TCPServerDispatcher::run() @ 0x12a417da in /usr/bin/clickhouse\n5. Poco::PooledThread::run() @ 0x12b7ab39 in /usr/bin/clickhouse\n6. Poco::ThreadImpl::runnableEntry(void*) @ 0x12b76b2a in /usr/bin/clickhouse\n7. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so\n8. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so\n")
worker_1      | Traceback (most recent call last):
worker_1      |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
worker_1      |     R = retval = fun(*args, **kwargs)
worker_1      |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
worker_1      |     return self.run(*args, **kwargs)
worker_1      |   File "/home/posthog/code/posthog/celery.py", line 247, in clickhouse_mutation_count
worker_1      |     rows = sync_execute(QUERY)
worker_1      |   File "/home/posthog/code/ee/clickhouse/client.py", line 156, in sync_execute
worker_1      |     raise err
worker_1      | clickhouse_driver.errors.ServerException: Code: None.
worker_1      | DB::Exception: Database `posthog` doesn't exist. Stack trace:
worker_1      | 
worker_1      | 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8b6cbba in /usr/bin/clickhouse
worker_1      | 1. DB::TCPHandler::runImpl() @ 0x104305e4 in /usr/bin/clickhouse
worker_1      | 2. DB::TCPHandler::run() @ 0x10441839 in /usr/bin/clickhouse
worker_1      | 3. Poco::Net::TCPServerConnection::start() @ 0x12a3fd4f in /usr/bin/clickhouse
worker_1      | 4. Poco::Net::TCPServerDispatcher::run() @ 0x12a417da in /usr/bin/clickhouse
worker_1      | 5. Poco::PooledThread::run() @ 0x12b7ab39 in /usr/bin/clickhouse
worker_1      | 6. Poco::ThreadImpl::runnableEntry(void*) @ 0x12b76b2a in /usr/bin/clickhouse
worker_1      | 7. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
worker_1      | 8. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
worker_1      | 
worker_1      | [2021-12-13 19:56:50,946: WARNING/ForkPoolWorker-1] Error on clickhouse:9000 ping: Unexpected EOF while reading bytes
worker_1      | [2021-12-13 19:56:50,949: WARNING/ForkPoolWorker-1] Connection was closed, reconnecting.
worker_1      | [2021-12-13 19:56:50,951: WARNING/ForkPoolWorker-1] Error on socket shutdown: [Errno 107] Socket not connected
worker_1      | [2021-12-13 19:56:50,960: ERROR/ForkPoolWorker-1] Task posthog.celery.clickhouse_part_count[ec7ba0ee-c249-45b3-912f-9447fc355f31] raised unexpected: ServerException("DB::Exception: Database `posthog` doesn't exist. Stack trace:\n\n0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8b6cbba in /usr/bin/clickhouse\n1. DB::TCPHandler::runImpl() @ 0x104305e4 in /usr/bin/clickhouse\n2. DB::TCPHandler::run() @ 0x10441839 in /usr/bin/clickhouse\n3. Poco::Net::TCPServerConnection::start() @ 0x12a3fd4f in /usr/bin/clickhouse\n4. Poco::Net::TCPServerDispatcher::run() @ 0x12a417da in /usr/bin/clickhouse\n5. Poco::PooledThread::run() @ 0x12b7ab39 in /usr/bin/clickhouse\n6. Poco::ThreadImpl::runnableEntry(void*) @ 0x12b76b2a in /usr/bin/clickhouse\n7. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so\n8. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so\n")
worker_1      | Traceback (most recent call last):
worker_1      |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
worker_1      |     R = retval = fun(*args, **kwargs)
worker_1      |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
worker_1      |     return self.run(*args, **kwargs)
worker_1      |   File "/home/posthog/code/posthog/celery.py", line 225, in clickhouse_part_count
worker_1      |     rows = sync_execute(QUERY)
worker_1      |   File "/home/posthog/code/ee/clickhouse/client.py", line 156, in sync_execute
worker_1      |     raise err
worker_1      | clickhouse_driver.errors.ServerException: Code: None.
worker_1      | DB::Exception: Database `posthog` doesn't exist. Stack trace:
worker_1      | 
worker_1      | 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8b6cbba in /usr/bin/clickhouse
worker_1      | 1. DB::TCPHandler::runImpl() @ 0x104305e4 in /usr/bin/clickhouse
worker_1      | 2. DB::TCPHandler::run() @ 0x10441839 in /usr/bin/clickhouse
worker_1      | 3. Poco::Net::TCPServerConnection::start() @ 0x12a3fd4f in /usr/bin/clickhouse
worker_1      | 4. Poco::Net::TCPServerDispatcher::run() @ 0x12a417da in /usr/bin/clickhouse
worker_1      | 5. Poco::PooledThread::run() @ 0x12b7ab39 in /usr/bin/clickhouse
worker_1      | 6. Poco::ThreadImpl::runnableEntry(void*) @ 0x12b76b2a in /usr/bin/clickhouse
worker_1      | 7. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
worker_1      | 8. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
worker_1      | 
```

Seeing that, I figured there might be some other migrations that didn't run. I checked the git repo, and it looks like there actually is supposed to be a `./bin/migrate` file, as we can see [here](https://github.com/PostHog/posthog/blob/master/bin/migrate). But the image being used in the docker-compose config doesn't seem to have it for some reason.

So I just copied the contents of the file and exec'd into the web container:
`docker-compose -f docker-compose.hobby.yml exec web bash`

And then ran:

```
set -e

python manage.py migrate
python manage.py migrate_clickhouse
python manage.py run_special_migrations
```

The clickhouse migrations ran, but `run_special_migrations` didn't exist as a command in the version of Posthog in the container:
`Unknown command: 'run_special_migrations'. Did you mean squashmigrations?`

I didn't dig into what `run_special_migrations` was supposed to do, but running through all those steps was what was required to get the hobby version of PostHog up and running on a DigitalOcean VM.

**Comment by marcushyett-ph** [comment]
Cc: @yakkomajuri @fuziontech could you possibly take a look - might be connected with changes for async migrations?

**Comment by yakkomajuri** [comment]
Yeah seems we're not copying over the new migrate file in docker compose. I'll look into this
