### ISSUE TITLE
Chunk Loading errors - Can't see "All Events"

### ISSUE THREAD

**Issue by eikooc** [PostHog/posthog#840]
**Describe the bug**
Can't see all events

**To Reproduce**
1. Fresh installation
2. Log some events
3. Click "All Events"

**Expected behavior**
See all events

**Screenshots**
`Uncaught (in promise) ChunkLoadError: Loading chunk 13 failed.
(missing: http://example.com/static/events.js)
    at Function.a.e (http://example.com/static/main.js:1:2975)
    at Object.events (http://example.com/static/main.js:51:121690)
    at http://example.com/static/main.js:51:125127
    at u (http://example.com/static/main.js:51:46027)
    at Generator._invoke (http://example.com/static/main.js:51:45780)
    at Generator.forEach.e.<computed> [as next] (http://example.com/static/main.js:51:46384)
    at n (http://example.com/static/main.js:6:75989)
    at l (http://example.com/static/main.js:6:76200)
    at http://example.com/static/main.js:6:76259
    at new Promise (<anonymous>)`

**Hosted or self hosted?:**
Self-hosted
- (if self-hosted) what version?
1.6.0

**Additional context**

**Comment by timgl** [comment]
Sorry for our super late response, this happens when you upgrade to a new version and you still have a tab open with the old version. @mariusandra we talked about this before but it makes updating app really painful.

**Comment by eikooc** [comment]
That might be one situation where it happens. This happened on a fresh installation though (and is still happening) 👍

**Comment by Twixes** [comment]
We weren't able to reproduce this on a fresh installation and unfortunately the issue is quite unavoidable between updates, though not that much of a nuisance in that case.
