### ISSUE TITLE
Database duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#934]
**Describe the bug**
Using the docker container, several times a minute I see these errors:
~~~
db_1     | 2020-06-06 17:27:39.337 UTC [13932] ERROR:  duplicate key value violates unique constraint "unique hash for each team"
db_1     | 2020-06-06 17:27:39.337 UTC [13932] DETAIL:  Key (team_id, hash)=(1, 488c3668a2cc3ab12c7760305209ca31) already exists.
db_1     | 2020-06-06 17:27:39.337 UTC [13932] STATEMENT:  INSERT INTO "posthog_elementgroup" ("team_id", "hash") VALUES (1, '488c3668a2cc3ab12c7760305209ca31') RETURNING "posthog_elementgroup"."id"
~~~

Related web traceback:
~~~
web_1    | [2020-06-06 17:28:40,646: ERROR/ForkPoolWorker-2] Task posthog.tasks.process_event.process_event[9844ff46-1d45-469e-933f-389a0ee0824b] raised unexpected: IntegrityError('duplicate key value violates unique constraint "unique distinct_id for team"\nDETAIL:  Key (team_id, distinct_id)=(1, 1728aad30958da-0c6791827bcce2-3a36560a-c0000-1728aad30967d3) already exists.\n')
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
web_1    |     return self.cursor.execute(sql, params)
web_1    | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "unique distinct_id for team"
web_1    | DETAIL:  Key (team_id, distinct_id)=(1, 1728aad30958da-0c6791827bcce2-3a36560a-c0000-1728aad30967d3) already exists.
web_1    |
web_1    |
web_1    | The above exception was the direct cause of the following exception:
web_1    |
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
web_1    |     R = retval = fun(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
web_1    |     return self.run(*args, **kwargs)
web_1    |   File "/code/posthog/tasks/process_event.py", line 170, in process_event
web_1    |     _capture(
web_1    |   File "/code/posthog/tasks/process_event.py", line 124, in _capture
web_1    |     Person.objects.create(team_id=team_id, distinct_ids=[str(distinct_id)])
web_1    |   File "/code/posthog/models/person.py", line 13, in create
web_1    |     person.add_distinct_ids(distinct_ids)
web_1    |   File "/code/posthog/models/person.py", line 40, in add_distinct_ids
web_1    |     self.add_distinct_id(distinct_id)
web_1    |   File "/code/posthog/models/person.py", line 34, in add_distinct_id
web_1    |     PersonDistinctId.objects.create(
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 433, in create
web_1    |     obj.save(force_insert=True, using=self.db)
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 745, in save
web_1    |     self.save_base(using=using, force_insert=force_insert,
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 782, in save_base
web_1    |     updated = self._save_table(
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 887, in _save_table
web_1    |     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 924, in _do_insert
web_1    |     return manager._insert(
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1204, in _insert
web_1    |     return query.get_compiler(using=using).execute_sql(returning_fields)
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1392, in execute_sql
web_1    |     cursor.execute(sql, params)
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
web_1    |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
web_1    |     return executor(sql, params, many, context)
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
web_1    |     return self.cursor.execute(sql, params)
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1    |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
web_1    |     return self.cursor.execute(sql, params)
web_1    | django.db.utils.IntegrityError: duplicate key value violates unique constraint "unique distinct_id for team"
web_1    | DETAIL:  Key (team_id, distinct_id)=(1, 1728aad30958da-0c6791827bcce2-3a36560a-c0000-1728aad30967d3) already exists.
~~~

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**
No errors

**Screenshots**

**Hosted or self hosted?:**
Self-hosted. 1.8.0

**Additional context**

**Comment by timgl** [comment]
@prawnsalad Thanks for raising this! These errors are expected [and caught correctly](https://github.com/PostHog/posthog/blob/master/posthog/tasks/process_event.py#L29), it's just a bit ugly. Those errors should definitely be muted

**Comment by tino** [comment]
You refer to a `.get()`, which won't raise an integrity error. The [integrity errors below it](https://github.com/PostHog/posthog/blob/master/posthog/tasks/process_event.py#L36) has a note that says: `# Catch race case when somebody already added this distinct_id between .get and .add_distinct_id`, which if true would mean that this should only occur very infrequently. However I see a very steady stream of these errors (as in 1000+ per 5m).

Also, this error appears to be with an ElementGroup insert, which I can't find in the code easily?

**Comment by timgl** [comment]
Yep, good catch. The actual place we catch this issue [is here](https://github.com/PostHog/posthog/blob/master/posthog/models/element_group.py#L31). It's the same concept though, we correctly catch it when trying to insert an element group but it already exists. It's not an issue, but it is ugly in the logs and would be great to be able to silence those.

**Comment by macobo** [comment]
@yakkomajuri this is ingestion-related feedback (not bug per say) - mind taking it into your backlog if still valid or closing?

**Comment by yakkomajuri** [comment]
Is this still happening @prawnsalad?

We completely re-did our ingestion pipeline over at https://github.com/PostHog/plugin-server so just double checking

**Comment by prawnsalad** [comment]
I had to stop using posthog a few months ago unfortunately, but I don't remember seeing them with the latest version in May - I can't be certain though sorry!

**Comment by yakkomajuri** [comment]
Alright, thank you! I'll close this but happy to reopen if there are new reports
