### ISSUE TITLE
Upgrade from 1.33.0 to 1.34.0 fails with "KeyError: 'sharded_session_recording_events'" in Kafka migration

### ISSUE THREAD

**Issue by jamilbk** [PostHog/posthog#9437]
## Bug description

Trying to upgrade PostHog from 1.33.0 to 1.34.x results in the upgrade hanging because one of the `posthog-migrate` pods launched by the `posthog-migrate` job is crashlooping because of an apparent `KeyError` in the kafka producer container. Not sure if there's something in my env causing the issue or what.

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: 1.33.0/fe82d214b66041c0a6e6026351a93da52e153163
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Here's the tail of the crashing pod:

```
posthog.User: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the PostHogConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
rest_hooks.Hook: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
<BrokerConnection node_id=bootstrap-0 host=posthog-posthog-kafka:9092 <connecting> [IPv4 ('10.245.206.116', 9092)]>: connecting to posthog-posthog-kafka:9092 [('10.245.206.116', 9092) IPv4]
Probing node bootstrap-0 broker version
<BrokerConnection node_id=bootstrap-0 host=posthog-posthog-kafka:9092 <connecting> [IPv4 ('10.245.206.116', 9092)]>: Connection complete.
Broker version identified as 2.5.0
Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
2022-04-16T17:51:55.997025Z [info     ] Schema out of sync on some clickhouse nodes! [ee.management.commands.sync_replicated_schema] out_of_sync_hosts={'chi-posthog-posthog-0-0-0': {'sharded_session_recording_events', 'sharded_events', 'writable_events', 'writable_session_recording_events'}}
2022-04-16T17:51:55.997352Z [info     ] Creating missing tables        [ee.management.commands.sync_replicated_schema] missing_tables={'sharded_session_recording_events', 'sharded_events', 'writable_events', 'writable_session_recording_events'}
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
<BrokerConnection node_id=0 host=posthog-posthog-kafka-0.posthog-posthog-kafka-headless.posthog.svc.cluster.local:9092 <connecting> [IPv4 ('10.244.0.114', 9092)]>: connecting to posthog-posthog-kafka-0.posthog-posthog-kafka-headless.posthog.svc.cluster.local:9092 [('10.244.0.114', 9092) IPv4]
    <BrokerConnection node_id=0 host=posthog-posthog-kafka-0.posthog-posthog-kafka-headless.posthog.svc.cluster.local:9092 <connecting> [IPv4 ('10.244.0.114', 9092)]>: Connection complete.
<BrokerConnection node_id=bootstrap-0 host=posthog-posthog-kafka:9092 <connected> [IPv4 ('10.245.206.116', 9092)]>: Closing connection.
utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/posthog/code/ee/management/commands/sync_replicated_schema.py", line 40, in handle
    self.create_missing_tables(out_of_sync_hosts, create_table_queries)
  File "/home/posthog/code/ee/management/commands/sync_replicated_schema.py", line 87, in create_missing_tables
    query = create_table_queries[table]
KeyError: 'sharded_session_recording_events'
Closing the Kafka producer with 0 secs timeout.
Proceeding to force close the producer since pending requests could not be completed within timeout 0.
```

**Comment by jamilbk** [comment]
Looks like the `create_table_queries` set is missing that key -- perhaps a migration got skipped? Though I'm showing the first three are done:
<img width="1212" alt="Screen Shot 2022-04-18 at 12 33 03 PM" src="https://user-images.githubusercontent.com/167144/163865565-22d0b174-3765-4f9e-901d-4e6fe1009b18.png">

**Comment by jamilbk** [comment]
Update: So I ended up getting the `0004` migration to run successfully (took a few tries). I then upgraded the chart (and app) using the standard upgrade command:

```
helm upgrade -f values.yaml --timeout 20m --namespace posthog posthog posthog/posthog --atomic --wait --wait-for-jobs --debug
```

And this error went away. Looks like that migration is necessary when upgrading from `1.33.0` to `1.34.2`?

**Comment by tiina303** [comment]
https://github.com/PostHog/posthog/pull/9465 should fix this problem
